
const prefijos = {
    a: "negación o privación de lo expresado por la base",
    an: "a-",
    ante: "anterioridad a otra cosa, en el espacio o en el tiempo",
    anti: "oposición o contrariedad a algo",
    co: "participación de alguien en lo expresado por la base",
    contra: "oposición a otra cosa",
    cuasi: "parecido o cercanía con otra cosa",
    des: "negación, privación o inversión del significado de la forma base",
    en: "comienzo de cierta acción o transformación de algo en otra cosa",
    em: "en-",
    entre: "posición o situación enmedio de otra cosa; a medias, no totalmente",
    ex: "abandono de un cargo o una posición",
    extra: "situación externa a otra cosa o más allá de ella",
    in: "negación de lo significado por la base",
    im: "in-",
    i: "in-",
    infra: ["Situación o posición de algo por debajo de otra cosa o de carácter menor o inferior a eso", "inferior, menos que, por debajo de"],
    inter: "relación entre dos cosas o situación en medio de ellas",
    intra: "posición dentro o en el interior de algo",
    mini: "menor dimensión o tamaño de lo común",
    para: "parecido o paralelo con otra cosa, o estado o carácter semejante a otra",
    pos: "posterioridad a algo u ocurrencia después de algo",
    post: "pos-",
    pre: "anterioridad a cierto estado o acontecimiento antes de otra cosa",
    re: ["acción repetida", "mayor grado de una cualidad"],
    sub: "ocurrencia por debajo de cierta superficie o de cierto grado; tratamiento dependiente de otra cosa",
    tras: "ocurrencia o situación más allá de algo, de manifestación a través de otra cosa o de paso de un lugar a otro",
    trans: "tras-",
    ambi: "que al mismo tiempo tiene dos aptitudes o valores",
    bi: "que tiene dos características",
    bis: "bi-",
    cent: "que vale, tiene o consta de cien",
    centi: "cent-",
    cuadr: "que vale, tiene o consta de cuatro",
    cuadri: "cuadr-",
    cuatri: "que vale, tiene o consta de cuatro",
    deca: "que vale, tiene o consta de diez",
    deci: "que es la décima parte de una unidad",
    dodeca: "que vale, tiene o consta de doce",
    endeca: "que vale, tiene o consta de once",
    enea: "que vale, tiene o consta de nueve",
    exa: "que vale, tiene o consta de seis",
    hecto: "que vale, tiene o consta de cien",
    hepta: "que vale, tiene o consta de siete",
    hexa: "que vale, tiene o consta de seis",
    mega: ["que vale, tiene o consta de un millón", "que se relaciona con algo de gran tamaño o importancia"],
    micro: ["que es la millonésima parte de una unidad", "que se relaciona con algo de dimensiones muy pequeñas o menores a las normales"],
    mili: "que es la milésima parte de una unidad",
    mono: "que tiene un valor único o una sola unidad o parte",
    multi: "que tiene muchos elementos o se repite varias veces",
    nano: "que es una milmillonésima parte de una unidad",
    octa: "que vale, tiene o consta de ocho",
    octo: "octa-",
    omni: "hecho, circunstancia o capacidad total o absoluta",
    pan: "que lo cubre todo",
    penta: "que vale, tiene o consta de cinco",
    pluri: "que hay muchos de su misma clase",
    poli: ["que tiene muchos o varios elementos", "que tiene mucho de algo"],
    semi: ["que es la mitad de algo", "lo inmediatamente anterior a algo; de forma incompleta"],
    sex: "que vale, tiene o consta de seis",
    tera: "que vale, tiene o consta de un billón",
    tetra: "que vale, tiene o consta de cuatro",
    tri: "que vale, tiene o consta de tres",
    uni: "que es uno solo; que es único",
    aero: ["propio o característico del aire", "relacionado con la aviación"],
    agr: "propio o relacionado con el campo",
    anfi: "a ambos lados, doble, alrededor",
    angio: "propio o relacionado con venas, vasos o conductos",
    antropo: "característico de los seres humanos o relacionado con ellos",
    archi: "de nivel superior a otros de la misma clase",
    arqueo: "relacionado con la antigüedad o propio de lo antiguo",
    auto: ["a sí mismo, de sí mismo", "del automóvil"],
    biblio: "relacionado con los libros o propio de ellos",
    bio: ["que se relaciona con la vida", "que se relaciona con la biología"],
    cardio: "característico o propio del corazón",
    céfalo: "relacionado con la cabeza o propio de ella",
    ciclo: "que tiene forma de rueda o tiene ruedas",
    circun: "rodeando algo, alrededor de su perímetro",
    cosmo: "que se relaciona con el cosmos, que tiene una concepción muy amplia o abarcadora",
    crono: "propio del tiempo o relacionado con una secuencia temporal",
    demo: "que es propio del pueblo o de los grupos humanos",
    endo: "en el interior de algo, dentro de",
    ecto: "fuera de algo, en el exterior de",
    entero: "relacionado con los intestinos",
    enter: "entero-",
    epi: "en la superficie o parte superior de algo",
    equi: "que es igual a otro en calidad o cantidad",
    esclero: "que ha sufrido un proceso de endurecimiento",
    exo: "fuera de, en el exterior de",
    fono: "que se relaciona con el sonido o la voz humana",
    fonía: "fono-",
    foto: ["relacionado con la luz", "que se relaciona con la fotografía"],
    gastro: "propio del estómago o relacionado con éste",
    gastr: "gastro-",
    geo: "de la Tierra o relacionado con la tierra",
    grafo: "propio de la escritura",
    hemi: "mitad de algo",
    hemo: ["hemato", "relacionado con la sangre"],
    hepato: "que pertenece o se relaciona con el hígado",
    hetero: "que es distinto a otro o difiere de algo",
    hidro: "propio del agua o relacionado con ella",
    hiper: "muy elevado sobre su estado normal",
    hipo: "menos de, por debajo de lo normal",
    homeo: "que tiene características semejantes a otro",
    homo: "de las mismas características que otro",
    iso: "que es igual a otro",
    macro: "muy grande, de mayor dimensión",
    maxi: "muy grande, muy largo, de magnitud mayor a la que se tiene por normal",
    morfo: "que pertenece o se relaciona con la forma de algo",
    neo: "que se constituye como una novedad a partir de otra cosa de la misma especie",
    neuro: "que es propio o se relaciona con los nervios, las neuronas o el sistema nervioso",
    orto: "que sigue lo correcto; que está conforme con lo correcto",
    osteo: "que es propio de los huesos o se relaciona con ellos",
    pato: "que se refiere a las enfermedades o dolencias",
    peri: "en torno a, alrededor de",
    podo: "que se relaciona con los pies o las patas",
    psico: "de la actividad mental, la conducta y los procesos psíquicos",
    radio: "que se relaciona con las radiaciones",
    radi: "radio-",
    retro: "por atrás, hacia atrás, hacia el pasado",
    seudo: "que es falso o aparenta ser lo que no es",
    sobre: "por encima de, en exceso",
    super: "por encima de lo común o normal, de gran calidad, de gran tamaño o de grandes dimensiones",
    supra: "que se ubica por encima de algo o es superior a él",
    tecno: "que es propio de la técnica",
    tele: ["que se transmite a distancia", "que es propio de la televisión o se relaciona con ella"],
    teo: "que es propio de los dioses o las religiones",
    teísmo: "teo-",
    termo: "que genera o conserva calor",
    ultra: ["que se ubica más allá de o del otro lado de algo", "que posee una característica o cualidad en grado sumo"],
    vice: "que está en el lugar de otro o en la posición inmediatamente inferior a él",
    viz: "vice-",
    vi: "vice-",
}
