import { GrammaticalPerson, StemChangeRuleId, MoodTense, MoodTenseMap, VerbConjugation, VerbConjugationAnnotation, VerbConjugationChanges, VerbForms, ConjugationOrDerivation, Participios } from "."
import { FailedTests } from "../test/test-support"
import { VerbAspectModifications } from "./regular-verb-rules"
import { version } from "./version.js"
import { license } from "./licencia.js"



export type InfinitiveClass = "-ar" | "-er" | "-ir"

// A family of verbs that conjugate the same depending on the termination.
// These start with a preceding hyphen to emphasize that the form is not a verb itself.
// However, this doesn't mean that all verbs with this termination conjugate the same way, 
// for example, the model for "-iar" is "vaciar", but "estudiar" is regular. 
export type VerboClaseConjugacional = "-acer" | "-ducir" | "-eer" | "-iar" | "-uir"


// El modelo de la conjugación.
// Para verbos regulares, no especifica un modelo.
export type ModeloConjugacional = 
        | "delinquir"
        | "caber"    | "caer"    | "conducir" | "dar"     | "decir"   | "dormir"
        | "enraizar" | "erguir"  | "estar"
        | "guiar"    | "haber"   | "hacer"    | "ir"      | "jugar"   | "leer"
        | "mover"    | "oír"     | "pedir"    | "poder"   | "poner" 
        | "querer"   | "reír"    | "saber"    | "salir"   | "seguir"  | "ser"
        | "tener"    | "traer"   | "vaciar"   | "venir"   | "ver"     | "volver"

// The rules for conjugating a single form of an irregular verb, such as: "IndPres", "IndImp"
export interface VerbAspectRulesWithFullyIrregularForms extends VerbAspectModifications {
    // morphology
    suffixes?: VerbConjugationChanges
    // suplication
    tema?: string
    forms?: VerbConjugation
    derivations?: {
        preserve_stress_from_base?: GrammaticalPerson[]
    }
}


export interface ReglasDeConjugaciónDeVerboExcepcionesLexicas extends Participios {
    // irregulares como: "ir", "ser"
    supletivo?: true,
    // Solo para casos irregulares, sí para "poder", no para "dormir"
    gerundio_tema_cambio_excepcional?: StemChangeRuleId
    imperativo_tú?: string | VerbForms
    vos?: string
    // ideas que probablemente no sirve mucho...
    tema_subjuntivo_yo?: string
    // FIX: narrow this type for exceptions, e.g. disallow add_suffix_to_infinitive
    reglas?: MoodTenseMap<VerbAspectRulesWithFullyIrregularForms>
}


// true means all tests passed, otherwise FailedTests lists the correct results for each failed test.
export type TestResults = true | FailedTests

// FIX: want to explain reason/origin/etemology for each change... this could help learners
export interface ReglasDeConjugaciónDeVerbo {
    // Used only by resolveConjugationClass(), to associate each portion of a collection of rules with the verb to which they apply.
    // These are ordered from most specific (the original infinitivo), to the most basic. Normally there are only one or two.
    // For example: ["retener", "tener"]
    infinitivos?: string[]
    clase_conjugacional?: VerboClaseConjugacional
    modelo?: ModeloConjugacional
    no_admite_prefijos?: true
    tema_presente_yo?: string | [string, string]
    sufijo_presente_yo?: string
    tema_pretérito?: string
    // tema especial del futuro / condicional
    tema_futuro?: string
    alternancia_vocálica?: StemChangeRuleId
    // Propiedades que no se generalizan bien, no productivos, no extrapolable.
    excepciones_léxicas?: ReglasDeConjugaciónDeVerboExcepcionesLexicas
    // Inidica que las pruebas pasan
    ok?: TestResults
}


// if a value is null, the verb is regular
// A verb that appears in this list has been verified with a test
export const verbos_con_cambios_morfológicos : {[infinitivo: string]: ReglasDeConjugaciónDeVerbo} = {
    abandonar:      {},
    abrasar:        {},
    abrazar:        {},
    abrir:          { excepciones_léxicas: { participio: ["abierto"] } },
    abrumar:        {},
    absolver:       { alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["absuelto"] } },
    absorber:       {},
    abstener:       { modelo: "tener" },
    abundar:        {},
    aburrir:        {},
    acabar:         {},
    acampar:        {},
    acarrear:       {},
    acceder:        {},
    acechar:        {},
    acelerar:       {},
    acentuar:       {},
    aceptar:        {},
    acercar:        {},
    acertar:        { alternancia_vocálica: "e:ie" },
    achicar:        {},
    acicalar:       {},
    acoger:         {},
    acometer:       {},
    acompañar:      {},
    acongojar:      {},
    aconsejar:      {},
    acontecer:      {},
    acordar:        { alternancia_vocálica: "o:ue" },
    acostar:        { alternancia_vocálica: "o:ue" },
    actualizar:     {},
    actuar:         {},
    acudir:         {},
    acusar:         {},
    adelgazar:      {},
    adherir:        { alternancia_vocálica: "e:ie" },
    adicionar:      {},
    adjuntar:       {},
    adobar:         {},
    adquirir:       { alternancia_vocálica: "i:ie" },
    adueñar:        {},
    advenir:        { modelo: "venir" },
    advertir:       { alternancia_vocálica: "e:ie" },
    afectar:        {},
    afeitar:        {},
    aferrar:        {},
    afirmar:        {},
    afligir:        {},
    aflojar:        {},
    aflorar:        {},
    afluir:         {},
    agachar:        {},
    agarrar:        {},
    agasajar:       {},
    agitar:         {},
    agolpar:        {},
    agradar:        {},
    agradecer:      {},
    agravar:        {},
    agregar:        {},
    agrupar:        {},
    aguantar:       {},
    aguar:          {},
    agudizar:       {},
    ahijar:         {},
    ahitar:         {},
    ahorrar:        {},
    ahusar:         {},
    ahuyentar:      {},
    airar:          {},
    aislar:         {},
    ajustar:        {},
    alargar:        {},
    alarmar:        {},
    albergar:       {},
    alcanzar:       {},
    alegrar:        {},
    alejar:         {},
    alentar:        { alternancia_vocálica: "e:ie" },
    aliar:          { modelo: "vaciar" },
    alimentar:      {},
    aliviar:        {},
    almorzar:       { alternancia_vocálica: "o:ue" },
    alojar:         {},
    alquilar:       {},
    // alquiler:    no es un verbo según el DEL de la RAE
    alterar:        {},
    alucinar:       {},
    alumbrar:       {},
    amaestrar:      {},
    amar:           {},
    amarrar:        {},
    amasar:         {},
    amnistiar:      { modelo: "vaciar" },
    amohinar:       {},
    amortiguar:     {},
    amparar:        {},
    ampliar:        { modelo: "vaciar" },
    anclar:         {},
    andar:          { tema_pretérito: "anduv" },
    anhelar:        {},
    animar:         {},
    aniquilar:      {},
    anotar:         {},
    ansiar:         { modelo: "vaciar" },
    anticuar:       {},
    anudar:         {},
    anunciar:       {},
    apacentar:      { alternancia_vocálica: "e:ie" },
    apaciguar:      {},
    apagar:         {},
    aparar:         {},
    aparecer:       {},
    apercibir:      {},
    apetecer:       {},
    aplastar:       {},
    aplaudir:       {},
    aplicar:        {},
    apoderar:       {},
    apostar:        { alternancia_vocálica: "o:ue" },
    apreciar:       {},
    aprehender:     {},
    aprender:       {},
    apresar:        {},
    apresurar:      {},
    apretar:        { alternancia_vocálica: "e:ie" },
    aprobar:        { alternancia_vocálica: "o:ue" },
    aprovechar:     {},
    apuntalar:      {},
    apuntar:        {},
    apurar:         {},
    aquilatar:      {},
    argumentar:     {},
    argüir:         {},
    armar:          {},
    arrancar:       {},
    arrasar:        {},
    arrastrar:      {},
    arreglar:       {},
    arremeter:      {},
    arrendar:       { alternancia_vocálica: "e:ie" },
    arrepentir:     { alternancia_vocálica: "e:ie" },
    arribar:        {},
    arriesgar:      {},
    arrimar:        {},
    arropar:        {},
    arrugar:        {},
    arruinar:       {},
    arrullar:       {},
    asaltar:        {},
    ascender:       { alternancia_vocálica: "e:ie" },
    asegurar:       {},
    asentar:        { alternancia_vocálica: "e:ie" },
    asentir:        { alternancia_vocálica: "e:ie" },
    asesinar:       {},
    asignar:        {},
    asir:           { tema_presente_yo: "asg" },
    asistir:        {},
    asolar:         { alternancia_vocálica: "o:ue" },      // FIX: also supports regular forms! Perhaps add an option to return both forms?
    asomar:         {},
    asombrar:       {},
    aspirar:        {},
    asustar:        {},
    atajar:         {},
    atar:           {},
    atardecer:      {},
    atemorizar:     {},
    atender:        { alternancia_vocálica: "e:ie" },
    atenuar:        {},
    atestiguar:     {},
    atiborrar:      {},
    atinar:         {},
    atorar:         {},
    atormentar:     {},
    atornillar:     {},
    atraer:         {},
    atravesar:      { alternancia_vocálica: "e:ie" },
    atrever:        {},
    atribuir:       {},
    atropellar:     {},
    aullar:         {},
    aumentar:       {},
    aunar:          {},
    aupar:          {},
    auscultar:      {},
    autoinfligir:   {},
    avenir:         { modelo: "venir" },
    avergonzar:     { alternancia_vocálica: "o:ue" },
    averiar:        { modelo: "vaciar" },
    averiguar:      {},
    avisar:         {},
    avizorar:       {},
    ayudar:         {},
    añadir:         {},
    bailar:         {},
    bajar:          {},
    bañar:          {},
    barrer:         {},
    basar:          {},
    bastar:         {},
    beber:          {},
    besar:          {},
    biografiar:     { modelo: "vaciar" },
    bordar:         {},
    bordear:        {},
    borrar:         {},
    brindar:        {},
    brotar:         {},
    bruñir:         {},
    bucear:         {},
    bullir:         {},
    buscar:         {},
    caber: {
        tema_presente_yo: "quep",
        tema_pretérito: "cup",
        tema_futuro: "cabr"
    },
    caer:           { tema_presente_yo: "caig" },
    calcular:       {},
    calentar:       { alternancia_vocálica: "e:ie" },
    calificar:      {},
    calmar:         {},
    calzar:         {},
    cambiar:        {},
    caminar:        {},
    cantar:         {},
    capacitar:      {},
    carcomer:       {},
    cargar:         {},
    casar:          {},
    catalogar:      {},
    categorizar:    {},
    causar:         {},
    cazar:          {},
    cegar:          { alternancia_vocálica: "e:ie" },
    celebrar:       {},
    cenar:          {},
    censurar:       {},
    centrar:        {},
    cepillar:       {},
    cerner:         { alternancia_vocálica: "e:ie" },
    cerrar:         { alternancia_vocálica: "e:ie" },
    ceñir:          { alternancia_vocálica: "e:i" },
    cesar:          {},
    charlar:        {},
    chatear:        {},
    chirriar:       { modelo: "vaciar" },
    chismear:       {},
    chocar:         {},
    chupar:         {},
    cimentar:       { alternancia_vocálica: "e:ie" },    // FIX: various irregularities
    circular:       {},
    circunvenir:    { modelo: "venir" },
    citar:          {},
    clavar:         {},
    cobrar:         {},
    cocer:          { alternancia_vocálica: "o:ue" },       // FIX: various irregularities
    cocinar:        {},
    codiciar:       {},
    codificar:      {},
    coincidir:      {},
    colar:          { alternancia_vocálica: "o:ue" },
    colgar:         { alternancia_vocálica: "o:ue" },
    colindar:       {},
    colocar:        {},
    colorar:        {},
    combar:         {},
    comenzar:       { alternancia_vocálica: "e:ie" },
    comer:          {},
    compartir:      {},
    compensar:      {},
    competir:       { alternancia_vocálica: "e:i" },
    completar:      {},
    comparar:       {},
    complicar:      {},
    comprar:        {},
    comprender:     {},
    comprobar:      { alternancia_vocálica: "o:ue" },
    comprometer:    {},
    comunicar:      {},
    concentrar:     {},
    conceptuar:     {},
    concertar:      { alternancia_vocálica: "e:ie" },
    concienciar:    {},
    concluir:       {},
    concordar:      { alternancia_vocálica: "o:ue" },
    condenar:       {},
    condescender:   { alternancia_vocálica: "e:ie" },
    condicionar:    {},
    conducir:       { clase_conjugacional: "-ducir", tema_pretérito: "conduj" },  // FIX: linguist: how can this pattern be generalized: "pretérito fuerte con -j" ?
    conectar:       {},
    confeccionar:   {},
    conferir:       { alternancia_vocálica: "e:ie" },
    confesar:       { alternancia_vocálica: "e:ie" },
    confiar:        { modelo: "vaciar" },
    confirmar:      {},
    confluir:       {},
    conformar:      {},
    confortar:      {},
    confundir:      {},
    congelar:       {},
    congestionar:   {},
    congregar:      {},
    conjugar:       { modelo: null },
    conjurar:       {},
    conmover:       { alternancia_vocálica: "o:ue" },
    conocer:        {},
    conquerir:      { alternancia_vocálica: "e:ie" },
    conquistar:     {},
    conseguir:      { alternancia_vocálica: "e:i" },
    consensuar:     {},
    consentir:      { alternancia_vocálica: "e:ie" },
    conservar:      {},
    considerar:     {},
    consistir:      {},
    consolar:       { alternancia_vocálica: "o:ue" },
    constatar:      {},
    constituir:     {},
    construir:      {},
    consultar:      {},
    consumir:       {},
    contactar:      {},
    contagiar:      {},
    contaminar:     {},
    contar:         { alternancia_vocálica: "o:ue" },
    contender:      { alternancia_vocálica: "e:ie" },
    contener:       {},
    contestar:      {},
    continuar:      {},
    contraer:       {},
    contrariar:     { modelo: "vaciar" },
    contrarrestar:  {},
    contratar:      {},
    contravenir:    { modelo: "venir" },
    contribuir:     {},
    controlar:      {},
    convenir:       { modelo: "venir" },
    conversar:      {},
    convertir:      { alternancia_vocálica: "e:ie" },
    corregir:       { alternancia_vocálica: "e:i" },
    correr:         {},
    corresponder:   {},
    corroer:        {},
    cortar:         {},
    coser:          {},
    costar:         { alternancia_vocálica: "o:ue" },
    crear:          {},
    crecer:         {},
    creer:          {},
    criar:          { modelo: "vaciar" },
    cruzar:         {},
    cuadrar:        {},
    cubrir:         { excepciones_léxicas: { participio: ["cubierto"] } },
    cuestionar:     {},
    cuidar:         {},
    cultivar:       {},
    cumplir:        {},
    curar:          {},
    currar:         {},
    custodiar:      {},
    dañar:          {},
    dar:            {
        modelo: "dar",
        // FIX: linguist: unclear
        excepciones_léxicas: {
            reglas: {
                // The default "-ar" verb pattern of accent the last sylable doesn't apply to vos forms of "dar", since "dás" is only one sylable
                IndPres: { suffixes: { s1: ["oy"],                                           p2: ["ais"],                       vos: null } },
                SubPres: { suffixes: { s1: ["é"],                s3: ["é"],                  p2: ["eis"] } },
                IndPret: { suffixes: { s1: ["i"], s2: ["iste"],  s3: ["io"],   p1: ["imos"], p2: ["isteis"], p3: ["ieron"] } },
                CmdPos:  { suffixes: {                           s3: ["é"],                                                     vos: null  } },
                CmdNeg:  { suffixes: {                           s3: ["é"],                  p2: ["eis"]} },
            }
        }
    },
    debatir:        {},
    deber:          {},
    debilitar:      {},
    decaer:         {},
    decidir:        {},
    decir:          {
        modelo: "decir", 
        tema_presente_yo: "dig",
        tema_pretérito: "dij",
        tema_futuro: "dir",
        alternancia_vocálica: "e:i",
        excepciones_léxicas: {
            participio: ["dicho"],
            gerundio: ["diciendo"],
            imperativo_tú: "di"
        }
    },
    declarar:       {},
    declinar:       {},
    dedicar:        {},
    defender:       { alternancia_vocálica: "e:ie" },
    deferir:        { alternancia_vocálica: "e:ie" },
    definir:        {},
    deformar:       {},
    degollar:        { alternancia_vocálica: "o:ue" },
    dejar:          {},
    deleitar:       {},
    delinquir:      {},
    delirar:        {},
    demoler:        { alternancia_vocálica: "o:ue" },
    demonizar:      {},
    demostrar:      { alternancia_vocálica: "o:ue" },
    denegar:        { alternancia_vocálica: "e:ie" },
    depender:       {},
    depositar:      {},
    depredar:       {},
    derramar:       {},
    derretir:       { alternancia_vocálica: "e:i" },
    derribar:       {},
    derrotar:       {},
    derruir:        {},
    desafiar:       { modelo: "vaciar" },
    desaguar:       {},
    desahijar:      {},
    desahogar:      {},
    desahuciar:     {},
    desalentar:     { alternancia_vocálica: "e:ie" },
    desaparecer:    {},
    desaprobar:     { alternancia_vocálica: "o:ue" },
    desarrollar:    {},
    desasir:        { tema_presente_yo: "desasg" },
    desatender:     { alternancia_vocálica: "e:ie" },
    desatinar:      {},
    desavenir:      { modelo: "venir" },
    desayunar:      {},
    desbaratar:     {},
    desbordar:      {},
    descafeinar:    {},
    descansar:      {},
    descargar:      {},
    descender:      { alternancia_vocálica: "e:ie" },
    descolgar:      { alternancia_vocálica: "o:ue" },
    descolorar:     {},
    desconcentrar:  {},
    desconceptuar:  {},
    desconfiar:     { modelo: "vaciar" },
    desconectar:    {},
    descontar:      { alternancia_vocálica: "o:ue" },
    descreer:       {},
    describir:      { excepciones_léxicas: { participio: ["descrito"] } },
    descubrir:      { excepciones_léxicas: { participio: ["descubierto"] } },
    desdoblar:      {},
    desear:         {},
    desembocar:     {},
    desempeñar:     {},
    desenroscar:    {},
    desenvolver:    { modelo: "volver" },
    desesperanzar:  {},
    desesperar:     {},
    desestimar:     {},
    desfallecer:    {},
    desgajar:       {},
    desgarrar:      {},
    desgraciar:     {},
    deshabituar:    {},
    deshacer:       {},
    deshierbar:     {},
    deshumanizar:   {},
    desistir:       {},
    desleír:        { modelo: "reír" },
    deslizar:       {},
    desmontar:      {},
    desobedecer:    {},
    desosar:        { alternancia_vocálica: "o:ue" },
    desparramar:    {},
    despedir:       { alternancia_vocálica: "e:i" },
    despegar:       {},
    despellejar:    {},
    desperdiciar:   {},
    despertar:      { alternancia_vocálica: "e:ie" },
    desplegar:      { alternancia_vocálica: "e:ie" },
    desplomar:      {},
    desplumar:      {},
    despojar:       {},
    despotricar:    {},
    despreciar:     {},
    desprender:     {},
    desproveer:     { modelo: "leer" },
    despuntar:      {},
    destartalar:    {},
    desterrar:      { alternancia_vocálica: "e:ie" },
    destilar:       {},
    destituir:      {},
    destruir:       {},
    desvaír:        {},
    desvariar:      {},
    desviar:        { modelo: "vaciar" },
    desvirtuar:     {},
    detallar:       {},
    detener:        {},    // FIX: setting modelo causes a failure, but it should work     {modelo: "tener"},
    deteriorar:     {},
    determinar:     {},
    devaluar:       {},
    devastar:       {},
    devenir:        { modelo: "venir" },
    devolver:       { modelo: "volver" },
    dibujar:        {},
    dictar:         {},
    diferenciar:    {},
    diferir:        { alternancia_vocálica: "e:ie" },
    dificultar:     {},
    digerir:        { alternancia_vocálica: "e:ie" },
    dignar:         {},
    diluir:         {},
    dirigir:        {},
    discernir:      { alternancia_vocálica: "e:ie" },
    disciplinar:    {},
    disculpar:      {},
    diseñar:        {},
    disentir:       { alternancia_vocálica: "e:ie" },
    disfrutar:      {},
    disminuir:      {},
    disolver:       { modelo: "volver" },
    disparar:       {},
    disponer:       {},
    distender:      { alternancia_vocálica: "e:ie" },
    distinguir:     {},
    distribuir:     {},
    disuadir:       {},
    divertir:       { alternancia_vocálica: "e:ie" },
    dividir:        {},
    divorciar:      {},
    divulgar:       {},
    doblar:         {},
    doblegar:       {},
    documentar:     {},
    doler:          { alternancia_vocálica: "o:ue" },
    dorar:          {},
    dormir:         { modelo: "dormir", alternancia_vocálica: "o:ue" },
    duchar:         {},
    dudar:          {},
    durar:          {},
    echar:          {},
    efectuar:       {},
    efluir:         {},
    ejercer:        {},
    elaborar:       {},
    elegir:         { alternancia_vocálica: "e:i" },
    electrocutar:   {},
    elevar:         {},  // FIX: linguist: solo en varios regiones hay: alternancia_vocálica: "e:ie"
    eludir:         {},
    embadurnar:     {},
    embarcar:       {},
    embestir:       { alternancia_vocálica: "e:i" },
    emborrachar:    {},
    emigrar:        {},
    emitir:         {},
    empacar:        {},
    empachar:       {},
    empapar:        {},
    emparejar:      {},
    empatar:        {},
    empeorar:       {},
    emperejilar:    {},
    emperifollar:   {},
    empezar:        { alternancia_vocálica: "e:ie" },
    emplear:        {},
    emprender:      {},
    empujar:        {},
    enamorar:       {},
    encajar:        {},
    encaminar:      {},
    encantar:       {},
    encaramar:      {},
    encargar:       {},
    encender:       { alternancia_vocálica: "e:ie" },
    encerrar:       { alternancia_vocálica: "e:ie" },
    enchufar:       {},
    encoger:        {},
    encomendar:     { alternancia_vocálica: "e:ie" },
    encontrar:      { alternancia_vocálica: "o:ue" },
    enderezar:      {},
    enfermar:       {},
    enflaquecer:    {},
    enfrentar:      {},
    enfriar:        { modelo: "vaciar" },
    enfurecer:      {},
    enganchar:      {},
    engañar:        {},
    engordar:       {},
    enjugar:        {modelo: null},  // regular, no sigue el modelo de "jugar"
    enlazar:        {},
    enloquecer:     {},
    enmascarar:     {},
    enmendar:       { alternancia_vocálica: "e:ie" },
    enojar:         {},
    enraizar:       { modelo: "enraizar", alternancia_vocálica: "e:ie" },
    enredar:        {},
    enroscar:       {},
    ensamblar:      {},
    ensanchar:      {},
    enseñar:        {},
    ensuciar:       {},
    entender:       { alternancia_vocálica: "e:ie" },
    enterar:        {},
    enterrar:       { alternancia_vocálica: "e:ie" },
    entrar:         {},
    entrechocar:    {},
    entregar:       {},
    entrever:       { modelo: "ver" },
    entrevistar:    {},
    entristecer:    {},
    entumecer:      {},
    entusiasmar:    {},
    enviar:         { modelo: "vaciar" },
    envidiar:       {},
    envolver:       { modelo: "volver" },
    erguir:         {
        alternancia_vocálica: "e:ie",
        tema_presente_yo: "yerg",  // FIX: tema_presente_yo: ["irg", "yerg"],
        excepciones_léxicas: { gerundio: ["irguiendo"] }
    },
    errar:          {}, // FIX: tiene dos formas
    eructar:        {},
    escabullir:     {},
    escalar:        {},
    escanear:       {},
    escapar:        {},
    escoger:        {},
    esconder:       {},
    escribir:       { excepciones_léxicas: { participio: ["escrito"] } },
    escuchar:       {},
    esculpir:       {},
    esforzar:       { alternancia_vocálica: "o:ue" },
    espantar:       {},
    esparcir:       {},
    esperar:        {},
    espiar:         { modelo: "vaciar" },
    esquiar:        { modelo: "vaciar" },
    establecer:     {},
    estacionar:     {},
    estafar:        {},
    estandarizar:   {},
    estar: {
        sufijo_presente_yo: "oy",
        tema_pretérito: "estuv", 
        excepciones_léxicas: {
            imperativo_tú: "está",
            reglas: {
                IndPres: {suffixes: {           s2: ["ás"], s3: ["á"], p3: ["án"]}},
                SubPres: {suffixes: {s1: ["é"], s2: ["és"], s3: ["é"], p3: ["én"]}},
                CmdPos:  {suffixes: {                       s3: ["é"], p3: ["én"]}},
                CmdNeg:  {suffixes: {           s2: ["és"], s3: ["é"], p3: ["én"]}}
            }
        }
    },
    estatuir:       {},
    estimar:        {},
    estipular:      {},
    estofar:        {},
    estornudar:     {},
    estrangular:    {},
    estrechar:      {},
    estregar:       { alternancia_vocálica: "e:ie" },  // FIX: multiple forms
    estremecer:     {},
    estrenar:       {},
    estropear:      {},
    estudiar:       {},
    evadir:         {},
    evaluar:        {},
    evitar:         {},
    examinar:       {},
    exasperar:      {},
    exceder:        {},
    exceptuar:      {},
    excluir:        {},
    exhalar:        {},
    exigir:         {},
    existir:        {},
    expandir:       {},
    expedir:        { alternancia_vocálica: "e:i" },
    expiar:         { modelo: "vaciar" },
    explicar:       {},
    explorar:       {},
    exponer:        {},
    expresar:       {},
    extender:       { alternancia_vocálica: "e:ie" },
    extenuar:       {},
    extinguir:      {},
    extraer:        {},
    extrañar:       {},
    fabricar:       {},
    facilitar:      {},
    facturar:       {},
    fallar:         {},
    fallecer:       {},
    faltar:         {},
    fascinar:       {},
    felicitar:      {},
    festejar:       {},
    figurar:        {},
    fijar:          {},
    finalizar:      {},
    firmar:         {},
    flanquear:      {},
    flaquear:       {},
    flexionar:      {},
    flotar:         {},
    fluctuar:       {},
    fluir:          {},
    formar:         {},
    forzar:         { alternancia_vocálica: "o:ue" },
    fotografiar:    { modelo: "vaciar" },
    fraguar:        {},
    frecuentar:     {},
    fregar:         { alternancia_vocálica: "e:ie" },
    freír:          { modelo: "reír" },
    frotar:         {},
    fruncir:        {},
    fulgurar:       {},
    fumar:          {},
    funcionar:      {},
    fundir:         {},
    ganar:          {},
    gastar:         {},
    gemir:          { modelo: "pedir" },
    generar:        {},
    germinar:       {},
    girar:          {},
    gobernar:       { alternancia_vocálica: "e:ie" },
    gotear:         {},
    gozar:          {},
    grabar:         {},
    graduar:        {},
    granizar:       {},
    gritar:         {},
    gruir:          {},
    gruñir:         {},
    guardar:        {},
    guiar:          {
        modelo: "guiar",
        // clase_conjugacional: "-iar",
        // TODO: hay formas reformadas en la reforma ortográfica de la RAE de 2010, considera añadir estas formas
        // Otherwise, the accent is the only thing different from the regular forms
        excepciones_léxicas: {
            reglas: {
                IndPres: {stress_last_char_of_s123p3_stem: true,
                          suffixes: {                       s3: ["á"],       p2: ["ais"],           vos: ["as"] }},
                IndPret: {suffixes: {s1: ["e"],             s3: ["o"] }},
                SubPres: {stress_last_char_of_s123p3_stem: true,
                          suffixes: {                                        p2: ["eis"] }},
                CmdPos:  {stress_last_char_of_s123p3_stem: true,
                          suffixes: {                                                               vos: ["a"] }},
                CmdNeg:  {stress_last_char_of_s123p3_stem: true,
                          suffixes: {                                        p2: ["eis"] }},
            }
        }
    },
    guisar:         {},
    gustar:         {},
    haber: {
        tema_pretérito: "hub",
        tema_futuro: "habr",
        excepciones_léxicas: {
            supletivo: true,
            imperativo_tú: ["habe", "he"],
            reglas: {
                IndPres: { forms: { s1: ["he"], s2: ["has"], s3: ["hay", "ha"],     p1: ["hemos"],                     p3: ["han"],   vos: null} },
                SubPres: { tema: "hay" },
                CmdPos:  { tema: "hay",
                           forms: {                                                                  p2: ["habed"],                   vos: null} },
                CmdNeg:  { tema: "hay" },
            }
        }
    },
    habitar:        {},
    habituar:       {},
    hablar:         {},
    hacer:          {
        modelo: "hacer",
        clase_conjugacional: "-acer",
        tema_presente_yo: "hag",
        tema_pretérito: "hic",
        tema_futuro: "har",
        excepciones_léxicas: {
            participio: ["hecho"],
            imperativo_tú: "haz",
            reglas: {
                // FIX: linguist: should "hizo" be managed with sound preserving transformations?
                IndPret: { forms: {s3: ["hizo"]} }
            }
        }
    },
    halar:          {},
    hallar:         {},
    hartar:         {},
    heder:          { alternancia_vocálica: "e:ie" },
    helar:          { alternancia_vocálica: "e:ie" },
    hendir:         { alternancia_vocálica: "e:ie" },  // but not the "e:i" for IndPret...
    herir:          { alternancia_vocálica: "e:ie" },
    herrar:         { alternancia_vocálica: "e:ie" },
    hervir:         { alternancia_vocálica: "e:ie" },
    hilvanar:       {},
    hornear:        {},
    hospedar:       {},
    huir:           { /* se conjuga de forma regular, solo hay reglas especiales de ortografía */ },
    humanizar:      {},
    humillar:       {},
    hundir:         {},
    identificar:    {},
    ignorar:        {},
    igualar:        {},
    iluminar:       {},
    imaginar:       {},
    imbuir:         {},
    impedir:        { alternancia_vocálica: "e:i" },
    implantar:      {},
    implorar:       {},
    imponer:        {},
    importar:       {},
    imposibilitar:  {},
    impregnar:      {},
    impresionar:    {},
    imprimir:       {},
    inclinar:       {},
    incluir:        {},
    incrementar:    {},
    incubar:        {},
    indagar:        {},
    indexar:        {},
    indicar:        {},
    inferir:        { alternancia_vocálica: "e:ie" },
    infestar:       {},
    infligir:       {},
    influir:        {},
    informar:       {},
    infundir:       {},
    ingeniar:       {},
    ingerir:        { alternancia_vocálica: "e:ie" },
    incrustar:      {},
    ingresar:       {},
    inhalar:        {},
    iniciar:        {},
    injerir:        { alternancia_vocálica: "e:ie" },
    inmigrar:       {},
    inmiscuir:      {},
    inquietar:      {},
    inquirir:       { alternancia_vocálica: "i:ie" },
    inscribir:      { excepciones_léxicas: { participio: ["inscrito"] } },
    insertar:       {},
    insinuar:       {},
    insistir:       {},
    inspeccionar:   {},
    instalar:       {},
    instar:         {},
    instituir:      {},
    instruir:       {},
    intentar:       {},
    interactuar:    {},
    intercalar:     {},
    intercambiar:   {},
    interesar:      {},
    interferir:     { alternancia_vocálica: "e:ie" },
    interrogar:     {},
    interrumpir:    {},
    interpretar:    {},
    intervenir:     { modelo: "venir" },
    intrigar:       {},
    introducir:     {},
    intuir:         { /* modelo: "huir" */ },
    inundar:        {},
    invadir:        {},
    invertir:       { alternancia_vocálica: "e:ie" },
    investir:       { alternancia_vocálica: "e:i" },
    invitar:        {},
    ir: {
        modelo: "ir",
        no_admite_prefijos: true,
        tema_pretérito: "fu",
        sufijo_presente_yo: "oy",
        excepciones_léxicas: {
            supletivo: true,
            participio: ["ido"],
            gerundio: ["yendo"],
            reglas: {
                // The default "-ir" verb pattern of accent the last sylable doesn't apply to vos forms of "ir", since "ir" is only one sylable
                IndPres: { forms: { s1: ["voy"], s2: ["vas"],    s3: ["va"],   p1: ["vamos"],  p2: ["vais"],     p3: ["van"], vos: null } },
                SubPres: { tema: "vay" },
                IndPret: { forms: { s1: ["fui"], s2: ["fuiste"], s3: ["fue"],  p1: ["fuimos"], p2: ["fuisteis"], p3: ["fueron"] } },
                IndImp:  { forms: { s1: ["iba"], s2: ["ibas"],   s3: ["iba"],  p1: ["íbamos"], p2: ["ibais"],    p3: ["iban"] } },
                // IndFut: uses regular conjugation
                // IndCond: uses regular conjugation
                CmdPos:  { forms: {              s2: ["ve"],     s3: ["vaya"], p1: ["vayamos", "vamos"],         p3: ["vayan"], vos: ["andá"] } },
                // FIX: linguist: the relation of CmdNeg being derived from SubPres is a fixed rule, right? If so, I can move this into code...
                CmdNeg:  { tema: "vay" },
            }
        }
    },
    irritar:        {},
    jactar:         {},
    jalar:          {},
    jubilar:        {},
    jugar: {
        // FIX: SubPres: vos spelling differs by region: vos: ["juegues", "*jugués"]
        alternancia_vocálica: "u:ue",
    },
    juntar:         {},
    jurar:          {},
    justificar:     {},
    juzgar:         {},
    lagrimear:      {},
    lamentar:       {},
    largar:         {},
    lastimar:       {},
    lavar:          {},
    leer:           { modelo: "leer", clase_conjugacional: "-eer" },
    levantar:       {},
    licenciar:      {},
    limpiar:        {},
    llamar:         {},
    llegar:         {},
    llenar:         {},
    llevar:         {},
    llorar:         {},
    llover:         {alternancia_vocálica: "o:ue"},   // FIX: conjugate_only: ["s3"]},
    localizar:      {},
    lograr:         {},
    luchar:         {},
    lucir:          {},
    lustrar:        {},
    maldecir:       { modelo: "decir" },
    malgastar:      {},
    malquerer:      { modelo: "querer" },
    mandar:         {},
    manejar:        {},
    maniatar:       {},
    manifestar:     { alternancia_vocálica: "e:ie" },
    mantener:       {},
    maquillar:      {},
    marcar:         {},
    marchar:        {},
    martillar:      {},
    matar:          {},
    matchear:       {},
    maullar:        {},
    medir:          { alternancia_vocálica: "e:i" },
    meditar:        {},
    mejorar:        {},
    mencionar:      {},
    mendigar:       {},
    menguar:        {},
    menstruar:      {},
    mentar:         { alternancia_vocálica: "e:ie" },
    mentir:         { alternancia_vocálica: "e:ie" },
    merecer:        {},
    merendar:       { alternancia_vocálica: "e:ie" },
    meter:          {},
    mirar:          {},
    modelar:        {},
    modernizar:     {},
    molestar:       {},
    montar:         {},
    morder:         { alternancia_vocálica: "o:ue" },
    morir:          { alternancia_vocálica: "o:ue" },
    mostrar:        { alternancia_vocálica: "o:ue" },
    mover:          { modelo: "mover", alternancia_vocálica: "o:ue" },
    mudar:          {},
    multiplicar:    {},
    murmurar:       {},
    nacer:          {},
    nadar:          {},
    necesitar:      {},
    negar:          { alternancia_vocálica: "e:ie" },
    nevar:          {alternancia_vocálica: "e:ie"},       // FIX: conjugate_only: ["s3"]},
    nombrar:        {},
    notar:          {},
    nutrir:         {},
    obedecer:       {},
    obligar:        {},
    observar:       {},
    obstruir:       {},
    obtener:        { modelo: "tener" },
    ocasionar:      {},
    ocluir:         {},
    ocupar:         {},
    ocurrir:        {},
    odiar:          {},
    ofrecer:        {},
    ofuscar:        {},
    oír:            {
        // FIX: linguist: why is this a class?
        modelo: "oír", 
        tema_presente_yo: "oig",
        excepciones_léxicas: {
            reglas: {
                CmdPos:  { suffixes: {                                                      p2: ["íd"],          } },
            }
        }
    },
    oler:           { alternancia_vocálica: "o:ue" },
    olvidar:        {},
    operar:         {},
    organizar:      {},
    oponer:         {modelo: "poner"},
    originar:       {},
    orinar:         {},
    padecer:        {},
    pagar:          {},
    parar:          {},
    parecer:        {},
    parpadear:      {},
    participar:     {},
    partir:         {},
    partyar:        {},
    pasar:          {},
    pasear:         {},
    pasmar:         {},
    patinar:        {},
    patrullar:      {},
    pausar:         {},
    pedalear:       {},
    pedir:          { modelo: "pedir", alternancia_vocálica: "e:i" },
    pegar:          {},
    peinar:         {},
    penetrar:       {},
    pensar:         { alternancia_vocálica: "e:ie" },
    perder:         { alternancia_vocálica: "e:ie" },
    perforar:       {},
    permanecer:     {},
    permitir:       {},
    perpetrar:      {},
    perpetuar:      {},
    perseguir:      { alternancia_vocálica: "e:i" },
    pertenecer:     {},
    pervertir:      { alternancia_vocálica: "e:ie" },
    pesar:          {},
    pescar:         {},
    pestañear:      {},
    petrificar:     {},
    piar:           { modelo: "vaciar" },
    picar:          {},
    picotear:       {},
    pintar:         {},
    pisar:          {},
    planchar:       {},
    plasmar:        {},
    platicar:       {},
    plegar:         { alternancia_vocálica: "e:ie" },
    poblar:         { alternancia_vocálica: "o:ue" },
    poder:          {
        alternancia_vocálica: "o:ue",
        tema_pretérito: "pud",
        tema_futuro: "podr",
        excepciones_léxicas: { gerundio_tema_cambio_excepcional: "o:u" }
    },
    poner:          {
        modelo: "poner",
        tema_presente_yo: "pong",
        tema_pretérito: "pus",
        tema_futuro: "pondr",
        excepciones_léxicas: {
            participio: ["puesto"],
            imperativo_tú: "pon",
            reglas: {
                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }},
            }
        }
    },
    pordiosear:     {},
    portar:         {},
    posar:          {},
    poseer:         {},
    practicar:      {},
    precluir:       {},
    preferir:       { alternancia_vocálica: "e:ie" },
    preguntar:      {},
    prender:        {},
    preocupar:      {},
    preparar:       {},
    presenciar:     {},
    presentar:      {},
    presentir:      { alternancia_vocálica: "e:ie" },
    presionar:      {},
    prestar:        {},
    pretender:      {},
    prevenir:       { modelo: "venir" },
    prever:         { modelo: "ver" },
    principiar:     {},
    probar:         { alternancia_vocálica: "o:ue" },
    proceder:       {},
    procesar:       {},
    procurar:       {},
    producir:       {},
    proferir:       { alternancia_vocálica: "e:ie" },
    prohibir:       {},
    prohijar:       {},
    proliferar:     {},
    prometer:       {},
    promover:       { alternancia_vocálica: "o:ue" },
    pronunciar:     {},
    proponer:       {},
    proporcionar:   {},
    propugnar:      {},
    proseguir:      { alternancia_vocálica: "e:i" },
    prostituir:     {},
    proteger:       {},
    proveer:        {},   // tiene dos participios
    provenir:       { modelo: "venir" },
    provocar:       {},
    publicar:       {},
    pudrir:         { excepciones_léxicas: { participio: ["podrido"] } },
    pulir:          {},
    puntuar:        {},
    quebrantar:     {},
    quebrar:        { alternancia_vocálica: "e:ie" },
    quedar:         {},
    quejar:         {},
    quemar:         {},
    querer:         {
        modelo: "querer",
        tema_pretérito: "quis",
        tema_futuro: "querr",
        alternancia_vocálica: "e:ie"
    },
    quitar:         {},
    ramificar:      {},
    raspar:         {},
    rastrear:       {},
    realizar:       {},
    reanudar:       {},
    rebanar:        {},
    rebelar:        {},
    recetar:        {},
    rechazar:       {},
    rechinar:       {},
    recibir:        {},
    reciclar:       {},
    reclamar:       {},
    recluir:        {},
    recobrar:       {},
    recoger:        {},
    recolectar:     {},
    recomendar:     { alternancia_vocálica: "e:ie" },
    recomenzar:     { alternancia_vocálica: "e:ie" },
    reconfortar:    {},
    reconocer:      {},
    reconstituir:   {},
    reconstruir:    {},
    recontar:       { alternancia_vocálica: "o:ue" },
    reconvenir:     { modelo: "venir" },
    recordar:       { alternancia_vocálica: "o:ue" },
    recorrer:       {},
    recuperar:      {},
    recurrir:       {},
    redistribuir:   {},
    redituar:       {},
    reducir:        {},
    reemplazar:     {},
    reencontrar:    { alternancia_vocálica: "o:ue" },
    reenviar:       { modelo: "vaciar" },
    reevaluar:      {},
    referir:        { alternancia_vocálica: "e:ie" },
    refluir:        {},
    reformar:       {},
    reforzar:       { alternancia_vocálica: "o:ue" },
    refugiar:       {},
    refutar:        {},
    regalar:        {},
    regañar:        {},
    regar:          { alternancia_vocálica: "e:ie" },
    regir:          { alternancia_vocálica: "e:i" },
    registrar:      {},
    regresar:       {},
    regular:        {},
    rehilar:        {},
    rehogar:        {},
    rehuir:         {},
    rehusar:        {},
    reinstalar:     {},
    reír: {
        modelo: "reír",
        alternancia_vocálica: "e:ie",  // añado po DeepSeek 27 feb 2026
        // alternancia_vocálica: "i:í",  FIX: linguist: is there a vowel change rule?
        excepciones_léxicas: {
            gerundio: ["riendo"],
            participio: ["reído"],
            reglas: {
                // FIX: linguist: are there other reglas I can use?
                // FIX: must formalize the relationship of CmdPos on SubPres
                IndPres: {forms: {s1: ["río"], s2: ["ríes"], s3: ["ríe"], p1: ["reímos"], p2: ["reís"],  p3: ["ríen"],   vos: ["reís"], }},
                IndPret: {forms: {                           s3: ["rio"],                                p3: ["rieron"],}},
                SubPres: {tema: "rí",
                        //   forms: {s1: ["ría"], s2: ["rías"], s3: ["ría"], p1: ["riamos"], p2: ["riáis"], p3: ["rían"] }},
                          forms: {                           s3: ["ría"], p1: ["riamos"], p2: ["riáis"], p3: ["rían"] }},
                CmdPos:  {tema: "rí",
                          forms: {                                        p1: ["riamos"], p2: ["reíd"],                  vos: ["reí"]}}
            }
        }
    },
    relajar:        {},
    relucir:        {},
    rememorar:      {},
    remodelar:      {},
    remplazar:      {},
    renunciar:      {},
    repartir:       {},
    repasar:        {},
    replicar:       {},
    reposar:        {},
    reprimir:       {},
    resbalar:       {},
    resentir:       { alternancia_vocálica: "e:ie" },
    resistir:       {},
    respirar:       {},
    restar:         {},
    restaurar:      {},
    remendar:       { alternancia_vocálica: "e:ie" },
    remorder:       { alternancia_vocálica: "o:ue" },
    remover:        { alternancia_vocálica: "o:ue" },
    rendir:         { modelo: "pedir" },
    reñir:          { alternancia_vocálica: "e:i" },
    renovar:        { alternancia_vocálica: "o:ue" },
    reparar:        {},
    repercutir:     {},
    repetir:        { alternancia_vocálica: "e:i" },
    representar:    {},
    reprobar:       { alternancia_vocálica: "o:ue" },
    requerir:       { alternancia_vocálica: "e:ie" },
    resfriar:       { modelo: "vaciar" },
    resolver:       { modelo: "mover" },
    responder:      {},
    restituir:      {},
    resultar:       {},
    retener:        { modelo: "tener" },
    retornar:       {},
    retozar:        {},
    retribuir:      {},
    retumbar:       {},
    reunir:         { alternancia_vocálica: "u:ú" },
    revaluar:       {},
    revelar:        {},
    reventar:       { alternancia_vocálica: "e:ie" },
    revertir:       { alternancia_vocálica: "e:ie" },
    revisar:        {},
    revolver:       { modelo: "volver" },
    rezagar:        {},
    rimar:          {},
    robar:          {},
    rociar:         { modelo: "vaciar" },
    rodar:          { alternancia_vocálica: "o:ue" },
    rogar:          { alternancia_vocálica: "o:ue" },
    romper:         { excepciones_léxicas: { participio: ["roto"] } },
    rondar:         {},
    saber:          {
        tema_pretérito: "sup",
        tema_futuro: "sabr",
        excepciones_léxicas: {
            reglas: {
                // similar a caber
                IndPres: { forms: { s1: ["sé"] } },
                SubPres: { tema: "sep" },
                CmdPos:  { forms: {                                s3: ["sepa"],  p1: ["sepamos"],                     p3: ["sepan"] } },
                CmdNeg:  { tema: "sep" },
            }
        }
    },
    saborear:       {},
    sacar:          {},
    saciar:         {},
    sacudir:        {},
    sahumar:        {},
    salir:          {
        tema_presente_yo: "salg",
        tema_futuro: "saldr",
        excepciones_léxicas: { "imperativo_tú": "sal" }
    },
    salpimentar:    { alternancia_vocálica: "e:ie" },
    saludar:        {},
    santiguar:      {},
    satisfacer:     {modelo: "hacer"},
    secar:          {},
    seducir:        {},
    seguir:         {
        // NOTE: this does not conjugate as a "-uir" clase infinitivo
        tema_presente_yo: "sig",
        alternancia_vocálica: "e:i",
        excepciones_léxicas: { tema_subjuntivo_yo: "sig" }
    },
    seleccionar:    {},
    sellar:         {},
    sembrar:        { alternancia_vocálica: "e:ie" },
    sentar:         { alternancia_vocálica: "e:ie" },
    sentir:         { alternancia_vocálica: "e:ie" },
    separar:        {},
    ser:            {
        modelo: "ser",
        excepciones_léxicas: {
            supletivo: true,
            reglas: {
                IndPres: { forms: { s1: ["soy"], s2: ["eres"],   s3: ["es"],    p1: ["somos"],  p2: ["sois"],     p3: ["son"],    vos: ["sos"] } },
                IndImp:  { forms: { s1: ["era"], s2: ["eras"],   s3: ["era"],   p1: ["éramos"], p2: ["erais"],    p3: ["eran"]}},
                IndPret: { forms: { s1: ["fui"], s2: ["fuiste"], s3: ["fue"],   p1: ["fuimos"], p2: ["fuisteis"], p3: ["fueron"] } },
                SubPres: { tema: "se" },
                CmdPos:  { forms: {              s2: ["sé"],     s3: ["sea"],   p1: ["seamos"],                   p3: ["sean"],   vos: null} },
                CmdNeg:  { tema: "se" },
            }
        }
    },
    serrar:         { alternancia_vocálica: "e:ie" },
    servir:         { alternancia_vocálica: "e:i" },
    significar:     {},
    simplificar:    {},
    situar:         {},
    sobrecargar:    {},
    sobrecoger:     {},
    sobrehilar:     {},
    sobresalir:     {},
    sobrevenir:     { modelo: "venir" },
    sobrevivir:     {},
    sofreír:        { modelo: "reír" },
    solar:          { alternancia_vocálica: "o:ue" },
    soldar:         { alternancia_vocálica: "o:ue" },
    soler:          { alternancia_vocálica: "o:ue" },
    solicitar:      {},
    sollozar:       {},
    soltar:         { alternancia_vocálica: "o:ue" },
    solucionar:     {},
    someter:        {},
    sonar:          { alternancia_vocálica: "o:ue" },
    sonreír:        { modelo: "reír" },
    soñar:          { alternancia_vocálica: "o:ue" },
    soportar:       {},
    sorprender:     {},
    sortear:        {},
    sosegar:        { alternancia_vocálica: "e:ie" },
    sospechar:      {},
    sostener:       {},
    soterrar:       {},
    subir:          {},
    substituir:     {},
    substraer:      {},
    subvenir:       { modelo: "venir" },
    subvertir:      { alternancia_vocálica: "e:ie" },
    succionar:      {},
    suceder:        {},
    sudar:          {},
    sufrir:         {},
    sugerir:        { alternancia_vocálica: "e:ie" },
    sujetar:        {},
    suministrar:    {},
    suplicar:       {},
    suponer:        {},
    supurar:        {},
    surgir:         {},
    suscribir:      { excepciones_léxicas: { participio: ["suscrito"] } },
    suspender:      {},
    suspirar:       {},
    sustentar:      {},
    sustituir:      {},
    sustraer:       {},
    tallar:         {},
    tapar:          {},
    tapiar:         {},
    tardar:         {},
    tartamudear:    {},
    tatuar:         {},
    temblar: { alternancia_vocálica: "e:ie" },
    temer:          {},
    tender: { alternancia_vocálica: "e:ie" },
    tener: {
        modelo: "tener", 
        tema_presente_yo: "teng",
        tema_pretérito: "tuv",
        tema_futuro: "tendr",
        alternancia_vocálica: "e:ie",
        excepciones_léxicas: {
            imperativo_tú: "ten",
            reglas: {
                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }},
            }
        }
    },
    tentar:         { alternancia_vocálica: "e:ie" },
    terminar:       {},
    teñir:          { alternancia_vocálica: "e:i" },
    textear:        {},
    tipificar:      {},
    tirar:          {},
    titubear:       {},
    tocar:          {},
    tolerar:        {},
    tomar:          {},
    torcer:         { alternancia_vocálica: "o:ue" },
    tornar:         {},
    toser:          {},
    tostar:         { alternancia_vocálica: "o:ue" },
    trabajar:       {},
    traducir:       {},
    traer:          { tema_presente_yo: "traig", tema_pretérito: "traj" },
    transcender:    { alternancia_vocálica: "e:ie" },
    transcurrir:    {},
    transferir:     { alternancia_vocálica: "e:ie" },
    transformar:    {},
    transmitir:     {},
    transportar:    {},
    trapear:        {},
    trascender:     { alternancia_vocálica: "e:ie" },
    trasferir:      { alternancia_vocálica: "e:ie" },
    traspasar:      {},
    trastabillar:   {},
    tratar:         {},
    trepar:         {},
    triangular:     {},
    triturar:       {},
    trocar:         { alternancia_vocálica: "o:ue" },
    tronar:         { alternancia_vocálica: "o:ue" },
    tropezar:       { alternancia_vocálica: "e:ie" },
    tumbar:         {},
    turnar:         {},
    ubicar:         {},
    unir:           {},
    usar:           {},
    utilizar:       {},
    vaciar:         {
        modelo: "vaciar",
        clase_conjugacional: "-iar",
        // FIX: linguist: The accent is the only thing different from the regular forms
        // Is this due to an orthographic rule? or something else?
        excepciones_léxicas: {
            reglas: {
                IndPres: {stress_last_char_of_s123p3_stem: true},
                SubPres: {stress_last_char_of_s123p3_stem: true},
                CmdPos:  {stress_last_char_of_s123p3_stem: true},
                CmdNeg:  {stress_last_char_of_s123p3_stem: true,
                          suffixes: {                                        vos: null }},
            }
        }
    },
    vacilar:        {},
    valer:          { tema_presente_yo: "valg", tema_futuro: "valdr" },
    validar:        {},
    valuar:         {},
    variar:         { modelo: "vaciar" },
    velar:          {},
    vencer:         {},
    vender:         {},
    venir:          {
        modelo: "venir",
        tema_presente_yo: "veng",
        tema_pretérito: "vin",
        tema_futuro: "vendr",
        alternancia_vocálica: "e:ie",
        excepciones_léxicas: {
            gerundio: ["viniendo"],
            imperativo_tú: "ven",
            reglas: {
                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }},
            }
        }
    },
    ver:            {
        modelo: "ver",
        // parece que no conforma bien a estas reglas
        // sí prefijo_ind_pres_yo cambia, pero no con "g", y no con los mismos cambios
        // no aplican ni tema_pretérito ni tema_futuro ni alternancia_vocálica
        // el resto son excepciones_léxicas
        excepciones_léxicas: {
            gerundio: ["viendo"],
            participio: ["visto"],
            // hay varias excepciones_léxicas que probablemente tienen que ver con el hecho que ver es solo una sílaba
            reglas: {
                // p2 => accent dropped
                // The default "-er" verb pattern of accent the last sylable doesn't apply to vos forms of "ver", since "vés" is only one sylable
                IndPres: { suffixes: { s1: ["eo"],                                              p2: ["eis"],                        vos: null },
                           derivations: {preserve_stress_from_base: ["s2","s3","p2","p3"]}
                         },
                SubPres: { tema: "ve" },
                // accents dropped
                IndPret: { forms: { s1: ["vi"], s3: ["vio"] },
                           derivations: {preserve_stress_from_base: ["s1", "s3"]}
                        },
                IndImp: { tema: "ve" },
                CmdPos: { forms: {                      s3: ["vea"],           p1: ["veamos"],               p3: ["vean"],            vos: null },
                           derivations: {preserve_stress_from_base: ["s2"] }
                        },
                        // FIX: linguist: if CmdNeg always follows SubPres, can codify this
                CmdNeg: { tema: "ve" },
            }
        }
    },
    verter:         { alternancia_vocálica: "e:ie" },
    vestir:         { alternancia_vocálica: "e:i" },
    viajar:         {},
    vidriar:        { modelo: "vaciar" },
    vigilar:        {},
    violar:         {},
    virar:          {},
    visitar:        {},
    vivir:          {},
    volar:          {alternancia_vocálica: "o:ue"},
    volcar:         { alternancia_vocálica: "o:ue" },
    voltear:        {},
    volver:         { modelo: "volver", alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["vuelto"] } },
    votar:          {},
    xerografiar:    { modelo: "vaciar" },
    yacer:          {},
    zaherir:        { alternancia_vocálica: "e:ie" },
    zambuir:        {},
    zambullir:      {},
    zumbar:         {},
}


export function getAnnotations(infinitivo: string, modelo: ModeloConjugacional, mood_tense_derivation: ConjugationOrDerivation) : VerbConjugationAnnotation {
    const annotations: VerbConjugationAnnotation = {infinitivo, mood_tense_derivation, modelo, version, license}
    return annotations
}
