import { GrammaticalPerson, StemChangeRuleId, MoodTense, MoodTenseMap, VerbConjugation, VerbConjugationAnnotation, VerbConjugationChanges, ConjugationOrDerivation, Participios, FormaConjugada, Defectos } from "."
import { FailedTests } from "../test"
import { VerbAspectModifications } from "./regular-verb-rules"
import { version } from "./version.js"
import { license } from "./licencia.js"



export type InfinitiveClass = "-ar" | "-er" | "-ir"

// A family of verbs that conjugate the same depending on the termination.
// These start with a preceding hyphen to emphasize that the form is not a verb itself.
// However, this doesn't mean that all verbs with this termination conjugate the same way, 
// for example, the model for "-iar" is "vaciar", but "estudiar" is regular. 
// "-eír": comes from desleír, which is conjugated like "reír"
export type VerboClaseConjugacional = "-acer" | "-ducir" | "-eer" | "-eír" | "-iar" | "-uir"


// El modelo de la conjugación.
// Para verbos regulares, no especifica un modelo.
export type ModeloConjugacional = 
        | "delinquir"
        | "andar"    | "caber"    | "caer"     | "conducir" | "conocer" | "dar"     | "decir"   | "dormir"
        | "enraizar" | "erguir"   | "estar"
        | "guiar"    | "haber"    | "hacer"    | "ir"       | "jugar"   | "leer"
        | "mover"    | "oír"      | "pedir"    | "poder"    | "poner" 
        | "querer"   | "reír"     | "saber"    | "salir"    | "seguir"  | "ser"
        | "tener"    | "traer"    | "vaciar"   | "venir"    | "ver"     | "volver"


// The rules for conjugating a single form of an irregular verb, such as: "IndPres", "IndImp"
export interface VerbAspectRulesWithFullyIrregularForms extends VerbAspectModifications {
    // morphology
    suffixes?: VerbConjugationChanges
    // suplication
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    tema?: FormaConjugada[]
    forms?: VerbConjugation
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    derivations?: {
        preserve_stress_from_base?: GrammaticalPerson[]
    }
}


export interface ReglasDeConjugaciónDeVerboExcepcionesLexicas extends Participios {
    // irregulares como: "ir", "ser"
    supletivo?: true,
    // Solo para casos irregulares, sí para "poder", no para "dormir"
    gerundio_tema_cambio_excepcional?: StemChangeRuleId
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    imperativo_tú?: FormaConjugada[]
    tema_subjuntivo_yo?: string
    // FIX: narrow this type for exceptions, e.g. disallow add_suffix_to_infinitive
    reglas?: MoodTenseMap<VerbAspectRulesWithFullyIrregularForms>
}


// true means all tests passed, otherwise FailedTests lists the correct results for each failed test.
export type TestResults = true | FailedTests

// FIX: want to explain reason/origin/etemology for each change... this could help learners
export interface ReglasDeConjugaciónDeVerbo {
    // Used only by resolveConjugationClass(), to associate each portion of a collection of rules with the verb to which they apply.
    // These are ordered from most specific (the original infinitivo), to the most basic. Normally there are only one or two.
    // For example: ["retener", "tener"]
    infinitivos?: string[]
    // null is used to override a model in a base verb, or a verb tht might appear to be a base. e.g. "conjugar"
    modelo?: ModeloConjugacional | null
    clase_conjugacional?: VerboClaseConjugacional
    defectos?: Defectos
    no_admite_prefijos?: true
    auxiliar?: true
    impersonal?: true
    // Hay verbos con formas multiples como erguir
    tema_presente_yo_del_modelo?: FormaConjugada[]
    // FIX: lingüista: Cuáles son las diferencias entre esto y excepciones_léxicas de sufijo?
    // dar -> 'd' + '-oy'
    // solo existe por modelos
    sufijo_presente_yo?: string
    tema_pretérito_del_modelo?: string
    // tema especial del futuro / condicional
    tema_futuro_del_modelo?: string
    alternancia_vocálica?: StemChangeRuleId
    // Propiedades que no se generalizan bien, no productivos, no extrapolable.
    excepciones_léxicas?: ReglasDeConjugaciónDeVerboExcepcionesLexicas
    // Inidica que las pruebas pasan
    ok?: TestResults
}


// if a value is null, the verb is regular
// A verb that appears in this list has been verified with a test
export const verbos_con_cambios_morfológicos : {[infinitivo: string]: ReglasDeConjugaciónDeVerbo} = {
    abandonar:      {},
    abatir:         {},
    abolir:         {},    // FIX: abolir no se conjuga como abolo, aboles, abola, etc. Se usan perífrasis: va a abolir
    abrasar:        {},
    abrazar:        {},
    abrir:          { excepciones_léxicas: { participio: ["abierto"] } },
    abrumar:        {},
    absolver:       { alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["absuelto"] } },
    absorber:       {},
    abstener:       { modelo: "tener" },
    abundar:        {},
    aburrir:        {},
    acabar:         { auxiliar: true },
    acaecer:        { defectos: {personas: ["s3", "p3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    acampar:        {},
    acarrear:       {},
    acceder:        {},
    acechar:        {},
    acelerar:       {},
    acentuar:       {},
    aceptar:        {},
    acercar:        {},
    acertar:        { alternancia_vocálica: "e:ie" },
    achicar:        {},
    acicalar:       {},
    acoger:         {},
    acometer:       {},
    acompañar:      {},
    acongojar:      {},
    aconsejar:      {},
    acontecer:      { tema_presente_yo_del_modelo: ["acontezc"], defectos: {personas: ["s3", "p3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    acordar:        { alternancia_vocálica: "o:ue" },
    acostar:        { alternancia_vocálica: "o:ue" },
    actualizar:     {},
    actuar:         {},
    acudir:         {},
    acumular:       {},
    acusar:         {},
    adelgazar:      {},
    adherir:        { alternancia_vocálica: "e:ie" },
    adicionar:      {},
    adjuntar:       {},
    adobar:         {},
    adquirir:       { alternancia_vocálica: "i:ie",
                      excepciones_léxicas: {
                            reglas: {
                                SubPres: { forms: { vos: [{"forma":"adquieras","uso":"Riop."},{"forma":"adquirás","uso":"C.Am."}]    }},
                            }
                        }     
                    },
    adueñar:        {},
    advenir:        { modelo: "venir" },
    advertir:       { alternancia_vocálica: "e:ie" },
    afectar:        {},
    afeitar:        {},
    aferrar:        {},
    afirmar:        {},
    afligir:        {},
    aflojar:        {},
    aflorar:        {},
    afluir:         {},
    agachar:        {},
    agarrar:        {},
    agasajar:       {},
    agitar:         {},
    agolpar:        {},
    agradar:        {},
    agradecer:      { tema_presente_yo_del_modelo: ["agradezc"]},
    agravar:        {},
    agredir:        {},   // FIX: Similar a abolir: falta presente de indicativo (excepto agredimos, agredís)
    agregar:        {},
    agrupar:        {},
    aguantar:       {},
    aguar:          {},
    agudizar:       {},
    ahijar:         {},
    ahitar:         {},
    ahorrar:        {},
    ahusar:         {},
    ahuyentar:      {},
    airar:          {},
    aislar:         {},
    ajustar:        {},
    alargar:        {},
    alarmar:        {},
    albergar:       {},
    alcanzar:       {},
    alegrar:        {},
    alejar:         {},
    alentar:        { alternancia_vocálica: "e:ie" },
    aliar:          { modelo: "vaciar" },
    alimentar:      {},
    aliviar:        {},
    almorzar:       { alternancia_vocálica: "o:ue" },
    alojar:         {},
    alquilar:       {},
    // alquiler:    no es un verbo según el DEL de la RAE
    alterar:        {},
    alucinar:       {},
    alumbrar:       {},
    amaestrar:      {},
    amanecer:       { tema_presente_yo_del_modelo: ["amanezc"] },
    amar:           {},
    amarrar:        {},
    amasar:         {},
    amnistiar:      { modelo: "vaciar" },
    amohinar:       {},
    amortiguar:     {},
    amparar:        {},
    ampliar:        { modelo: "vaciar" },
    añadir:         {},
    anclar:         {},
    andar:          { modelo: "andar",
                        auxiliar: true, 
                        tema_pretérito_del_modelo: "anduv",
                        excepciones_léxicas: {
                            reglas: {
                                IndPret: { suffixes: {                                  p3: ["ieron"]}},
                            }
                        }
                    },
    anhelar:        {},
    anidar:         {},
    animar:         {},
    aniquilar:      {},
    anochecer:      { tema_presente_yo_del_modelo: ["anochezc"] },
    anotar:         {},
    ansiar:         { modelo: "vaciar" },
    anticuar:       {},
    anudar:         {},
    anunciar:       {},
    apacentar:      { alternancia_vocálica: "e:ie" },
    apaciguar:      {},
    apagar:         {},
    aparar:         {},
    aparecer:       { tema_presente_yo_del_modelo: ["aparezc"]},
    apartar:        {},
    apercibir:      {},
    apetecer:       { tema_presente_yo_del_modelo: ["apetezc"]},
    aplastar:       {},
    aplaudir:       {},
    aplicar:        {},
    apoderar:       {},
    apostar:        { alternancia_vocálica: "o:ue" },
    apreciar:       {},
    aprehender:     {},
    aprender:       {},
    apresar:        {},
    apresurar:      {},
    apretar:        { alternancia_vocálica: "e:ie" },
    aprobar:        { alternancia_vocálica: "o:ue" },
    aprovechar:     {},
    apuntalar:      {},
    apuntar:        {},
    apurar:         {},
    aquilatar:      {},
    argüir:         {},
    argumentar:     {},
    armar:          {},
    arrancar:       {},
    arrasar:        {},
    arrastrar:      {},
    arreglar:       {},
    arremeter:      {},
    arrendar:       { alternancia_vocálica: "e:ie" },
    arrepentir:     { alternancia_vocálica: "e:ie" },
    arribar:        {},
    arriesgar:      {},
    arrimar:        {},
    arropar:        {},
    arrugar:        {},
    arruinar:       {},
    arrullar:       {},
    asaltar:        {},
    ascender:       { alternancia_vocálica: "e:ie" },
    asegurar:       {},
    asentar:        { alternancia_vocálica: "e:ie" },
    asentir:        { alternancia_vocálica: "e:ie" },
    asesinar:       {},
    asignar:        {},
    asir:           { tema_presente_yo_del_modelo: ["asg"] },
    asistir:        {},
    asolar:         { alternancia_vocálica: "o:ue" },      // FIX: also supports regular forms! Perhaps add an option to return both forms?
    asomar:         {},
    asombrar:       {},
    aspirar:        {},
    asustar:        {},
    atajar:         {},
    atañer:         { defectos: {personas: ["s3", "p3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    atar:           {},
    atardecer:      { tema_presente_yo_del_modelo: ["atardezc"], impersonal: true},
    atemorizar:     {},
    atender:        { alternancia_vocálica: "e:ie" },
    atenuar:        {},
    aterir:         {},   // FIX: Solo se usa en formas donde la raíz no lleva "i" tónica: atería, aterido; No se usa atero, ateres
    atestiguar:     {},
    atiborrar:      {},
    atinar:         {},
    atorar:         {},
    atormentar:     {},
    atornillar:     {},
    atraer:         { modelo: "traer" },
    atravesar:      { alternancia_vocálica: "e:ie" },
    atrever:        {},
    atribuir:       {},
    atropellar:     {},
    aullar:         {},
    aumentar:       {},
    aunar:          {},
    aupar:          {},
    auscultar:      {},
    autoinfligir:   {},
    avenir:         { modelo: "venir" },
    avergonzar:     { alternancia_vocálica: "o:ue" },
    averiar:        { modelo: "vaciar" },
    averiguar:      {},
    avisar:         {},
    avizorar:       {},
    ayudar:         {},
    bailar:         {},
    bajar:          {},
    balbucear:      {},
    balbucir:       {},   // FIX: Presente de indicativo: se usa más balbuceo que balbuzco (la forma regular ha desplazado a la irregular)
    bañar:          {},
    barrer:         {},
    basar:          {},
    bastar:         {},
    beber:          {},
    besar:          {},
    biografiar:     { modelo: "vaciar" },
    bordar:         {},
    bordear:        {},
    borrar:         {},
    brindar:        {},
    brotar:         {},
    bruñir:         {},
    bucear:         {},
    bullir:         {},
    buscar:         {},
    caber:          { modelo: "caber",
                        tema_presente_yo_del_modelo: ["quep"],
                        tema_pretérito_del_modelo: "cup",
                        tema_futuro_del_modelo: "cabr"
                    },
    caer:           { tema_presente_yo_del_modelo: ["caig"] },
    calcular:       {},
    calentar:       { alternancia_vocálica: "e:ie" },
    calificar:      {},
    calmar:         {},
    calzar:         {},
    cambiar:        {},
    caminar:        {},
    cantar:         {},
    capacitar:      {},
    carcomer:       {},
    cargar:         {},
    casar:          {},
    catalogar:      {},
    categorizar:    {},
    causar:         {},
    cazar:          {},
    cegar:          { alternancia_vocálica: "e:ie" },
    celebrar:       {},
    cenar:          {},
    ceñir:          { alternancia_vocálica: "e:i" },
    censurar:       {},
    centrar:        {},
    cepillar:       {},
    cerner:         { alternancia_vocálica: "e:ie" },
    cerrar:         { alternancia_vocálica: "e:ie" },
    cesar:          {},
    charlar:        {},
    chatear:        {},
    chirriar:       { modelo: "vaciar" },
    chismear:       {},
    chocar:         {},
    chupar:         {},
    cimentar:       { alternancia_vocálica: "e:ie" },    // FIX: various irregularities
    circular:       {},
    circunvenir:    { modelo: "venir" },
    citar:          {},
    clavar:         {},
    cobrar:         {},
    cocer:          { alternancia_vocálica: "o:ue",
                      tema_presente_yo_del_modelo: ["cuez"],
                        excepciones_léxicas: {
                            participio: ["cocido","cocho"],
                            reglas: {
                                SubPres: {forms: {p1:["cozamos"], p2:["cozáis"],            vos: [{"forma": "cuezas","uso":"Riop."},{"forma":"cozás","uso":"C.Am."}]}},
                                CmdPos:  {forms: {p1:["cozamos"]}}
                            }
                        }
                    },
    cocinar:        {},
    codiciar:       {},
    codificar:      {},
    coincidir:      {},
    colar:          { alternancia_vocálica: "o:ue" },
    colgar:         { alternancia_vocálica: "o:ue" },
    colindar:       {},
    colocar:        {},
    colorar:        {},
    colorear:       {},
    combar:         {},
    comenzar:       { alternancia_vocálica: "e:ie" },
    comer:          {},
    comparar:       {},
    compartir:      {},
    compensar:      {},
    competir:       { alternancia_vocálica: "e:i" },
    completar:      {},
    complicar:      {},
    comprar:        {},
    comprender:     {},
    comprobar:      { alternancia_vocálica: "o:ue" },
    comprometer:    {},
    comunicar:      {},
    concentrar:     {},
    conceptuar:     {},
    concernir:      { defectos: {personas: ["s3", "p3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },

    concertar:      { alternancia_vocálica: "e:ie" },
    concienciar:    {},
    concluir:       {},
    concordar:      { alternancia_vocálica: "o:ue" },
    condenar:       {},
    condescender:   { alternancia_vocálica: "e:ie" },
    condicionar:    {},
    conducir:       { clase_conjugacional: "-ducir", tema_presente_yo_del_modelo: ["conduzc"], tema_pretérito_del_modelo: "conduj" },  // FIX: linguist: how can this pattern be generalized: "pretérito fuerte con -j" ?
    conectar:       {},
    confeccionar:   {},
    conferir:       { alternancia_vocálica: "e:ie" },
    confesar:       { alternancia_vocálica: "e:ie" },
    confiar:        { modelo: "vaciar" },
    confirmar:      {},
    confluir:       {},
    conformar:      {},
    confortar:      {},
    confundir:      {},
    congelar:       {},
    congestionar:   {},
    congregar:      {},
    conjugar:       { modelo: null },   // regular, no sigue el modelo de "jugar"
    conjurar:       {},
    conmover:       { alternancia_vocálica: "o:ue" },
    conocer:        { modelo: "conocer", tema_presente_yo_del_modelo: ["conozc"] },
    conquerir:      { alternancia_vocálica: "e:ie" },
    conquistar:     {},
    conseguir:      { alternancia_vocálica: "e:i" },
    consensuar:     {},
    consentir:      { alternancia_vocálica: "e:ie" },
    conservar:      {},
    considerar:     {},
    consistir:      {},
    consolar:       { alternancia_vocálica: "o:ue" },
    constatar:      {},
    constituir:     {},
    construir:      {},
    consultar:      {},
    consumir:       {},
    contactar:      {},
    contagiar:      {},
    contaminar:     {},
    contar:         { alternancia_vocálica: "o:ue",
                      excepciones_léxicas: {
                            reglas: {
                                SubPres: { forms: { vos: [{"forma":"cuentes","uso":"Riop."},{"forma":"contés","uso":"C.Am."}] }}
                            }
                        }
                    },
    contender:      { alternancia_vocálica: "e:ie" },
    contener:       {},
    contestar:      {},
    continuar:      {},
    contraer:       {},
    contrariar:     { modelo: "vaciar" },
    contrarrestar:  {},
    contratar:      {},
    contravenir:    { modelo: "venir" },
    contribuir:     {},
    controlar:      {},
    convenir:       { modelo: "venir" },
    conversar:      {},
    convertir:      { alternancia_vocálica: "e:ie" },
    convivir:       {},
    corear:         {},
    corregir:       { alternancia_vocálica: "e:i" },
    correr:         {},
    corresponder:   {},
    corroer:        {},
    cortar:         {},
    coser:          {},
    costar:         { alternancia_vocálica: "o:ue" },
    crear:          {},
    crecer:         { tema_presente_yo_del_modelo: ["crezc"] },
    creer:          {},
    criar:          { modelo: "vaciar",   // FIX: hay varias formas con dos variantes: tb. pre-2010
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: {suffixes: {p2: ["ais"], vos: ["as"]} },  // elimina tilde por RAE-2010
                                IndPret: {suffixes: {s1: ["e"], s3: ["o"]} },  // elimina tilde por RAE-2010
                                SubPres: {suffixes: {p2: ["eis"]}},  // elimina tilde por RAE-2010
                                        //   forms: {vos: {atípicos: [{forma: "criés"}]}}},
                                CmdPos:  {suffixes: {vos: ["a"]} }  // elimina tilde por RAE-2010
                            }
                        }
                    },
    cruzar:         {},
    cuadrar:        {},
    cubrir:         { excepciones_léxicas: { participio: ["cubierto"] } },
    cuestionar:     {},
    cuidar:         {},
    cultivar:       {},
    cumplir:        {},
    curar:          {},
    currar:         {},
    custodiar:      {},
    dañar:          {},
    dar:            { modelo: "dar",
                      sufijo_presente_yo: "oy",
                      excepciones_léxicas: {
                            reglas: {
                                // The default "-ar" verb pattern of accent the last sylable doesn't apply to vos forms of "dar", since "dás" is only one sylable
                                IndPres: { suffixes: {                                                       p2: ["ais"],                       vos: null } },
                                SubPres: { suffixes: { s1: ["é"],                s3: ["é"],                  p2: ["eis"],                       vos: null } },
                                IndPret: { suffixes: { s1: ["i"], s2: ["iste"],  s3: ["io"],   p1: ["imos"], p2: ["isteis"], p3: ["ieron"] } },
                                CmdPos:  { suffixes: {                           s3: ["é"],                                                     vos: null  } }
                            }
                        }
                    },
    debatir:        {},
    deber:          { auxiliar: true },
    debilitar:      {},
    decaer:         {},
    decidir:        {},
    decir:          { modelo: "decir", 
                        tema_presente_yo_del_modelo: ["dig"],
                        tema_pretérito_del_modelo: "dij",
                        tema_futuro_del_modelo: "dir",
                        alternancia_vocálica: "e:i",
                        excepciones_léxicas: {
                            participio: ["dicho"],
                            gerundio: ["diciendo"],
                            imperativo_tú: ["di"],
                        }
                    },
    declarar:       {},
    declinar:       {},
    dedicar:        {},
    defender:       { alternancia_vocálica: "e:ie" },
    deferir:        { alternancia_vocálica: "e:ie" },
    definir:        {},
    deformar:       {},
    degollar:       { alternancia_vocálica: "o:ue" },
    dejar:          {},
    deleitar:       {},
    delinquir:      {},
    delirar:        {},
    demoler:        { alternancia_vocálica: "o:ue" },
    demonizar:      {},
    demostrar:      { alternancia_vocálica: "o:ue" },
    denegar:        { alternancia_vocálica: "e:ie" },
    depender:       {},
    depositar:      {},
    depredar:       {},
    derramar:       {},
    derretir:       { alternancia_vocálica: "e:i" },
    derribar:       {},
    derrotar:       {},
    derruir:        {},
    desactivar:     {},
    desafiar:       { modelo: "vaciar" },
    desaguar:       {},
    desahijar:      {},
    desahogar:      {},
    desahuciar:     {},
    desalentar:     { alternancia_vocálica: "e:ie" },
    desaparecer:    { tema_presente_yo_del_modelo: ["desaparezc"]},
    desaprobar:     { alternancia_vocálica: "o:ue" },
    desarrollar:    {},
    desasir:        { tema_presente_yo_del_modelo: ["desasg"] },
    desatender:     { alternancia_vocálica: "e:ie" },
    desatinar:      {},
    desavenir:      { modelo: "venir" },
    desayunar:      {},
    desbaratar:     {},
    desbordar:      {},
    descafeinar:    { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    descansar:      {},
    descargar:      {},
    descartar:      {},
    descender:      { alternancia_vocálica: "e:ie" },
    descolgar:      { alternancia_vocálica: "o:ue" },
    descolorar:     {},
    desconcentrar:  {},
    desconceptuar:  {},
    desconectar:    {},
    desconfiar:     { modelo: "vaciar" },
    descontar:      { alternancia_vocálica: "o:ue" },
    descreer:       {},
    describir:      { excepciones_léxicas: { participio: ["descrito"] } },
    descubrir:      { excepciones_léxicas: { participio: ["descubierto"] } },
    desdoblar:      {},
    desear:         {},
    desembocar:     {},
    desempeñar:     {},
    desenroscar:    {},
    desenvolver:    { modelo: "volver" },
    desesperanzar:  {},
    desesperar:     {},
    desestimar:     {},
    desfallecer:    { tema_presente_yo_del_modelo: ["desfallezc"] },
    desgajar:       {},
    desgarrar:      {},
    desgraciar:     {},
    deshabituar:    {},
    deshacer:       { modelo: "hacer" },
    deshierbar:     {},
    deshumanizar:   {},
    desistir:       {},
    desleír:        { modelo: "reír",
                        clase_conjugacional: "-eír",
                        excepciones_léxicas: {
                            reglas: {
                                //                      no existe variante sin tilde proviene de "reír"
                                IndPret: { forms: { s3: ["deslió"]   }},
                                //                      no existe variante sin tilde proviene de "reír"
                                SubPres: { forms: { p2: ["desliáis"]   }},
                            }
                        }
                    },
    deslizar:       {},
    desmontar:      {},
    desobedecer:    { tema_presente_yo_del_modelo: ["desobedezc"] },
    desosar:        { alternancia_vocálica: "o:ue" },
    desparramar:    {},
    despedir:       { alternancia_vocálica: "e:i" },
    despegar:       {},
    despellejar:    {},
    desperdiciar:   {},
    despertar:      { alternancia_vocálica: "e:ie" },
    desplegar:      { alternancia_vocálica: "e:ie" },
    desplomar:      {},
    desplumar:      {},
    despojar:       {},
    despotricar:    {},
    despreciar:     {},
    desprender:     {},
    desproveer:     { modelo: "leer" },
    despuntar:      {},
    destartalar:    {},
    desterrar:      { alternancia_vocálica: "e:ie" },
    destilar:       {},
    destituir:      {},
    destrozar:      {},
    destruir:       {},
// desvaír:        {},   // FIX:
    desvariar:      {},
    desviar:        { modelo: "vaciar" },
    desvirtuar:     {},
    detallar:       {},
    detener:        {},    // FIX: setting modelo causes a failure, but it should work     {modelo: "tener"},
    deteriorar:     {},
    determinar:     {},
    devaluar:       {},
    devastar:       {},
    devenir:        { modelo: "venir" },
    devolver:       { modelo: "volver" },
    dibujar:        {},
    dictar:         {},
    diferenciar:    {},
    diferir:        { alternancia_vocálica: "e:ie" },
    dificultar:     {},
    digerir:        { alternancia_vocálica: "e:ie" },
    dignar:         {},
    diluir:         {},
    dirigir:        {},
    discernir:      { alternancia_vocálica: "e:ie" },
    disciplinar:    {},
    disculpar:      {},
    diseñar:        {},
    disentir:       { alternancia_vocálica: "e:ie" },
    disfrutar:      {},
    disminuir:      {},
    disolver:       { modelo: "volver" },
    disparar:       {},
    disponer:       {},
    distender:      { alternancia_vocálica: "e:ie" },
    distinguir:     {},
    distribuir:     {},
    disuadir:       {},
    divertir:       { alternancia_vocálica: "e:ie" },
    dividir:        {},
    divorciar:      {},
    divulgar:       {},
    doblar:         {},
    doblegar:       {},
    documentar:     {},
    doler:          { alternancia_vocálica: "o:ue" },
    dorar:          {},
    dormir:         { modelo: "dormir", alternancia_vocálica: "o:ue" },
    duchar:         {},
    dudar:          {},
    durar:          {},
    echar:          {},
    efectuar:       {},
    efluir:         {},
    ejercer:        { tema_presente_yo_del_modelo: ["ejerz"] },  // no sigue el modelo de conocer, no usa "zc"
    elaborar:       {},
    electrocutar:   {},
    elegir:         { alternancia_vocálica: "e:i" },
    elevar:         {},  // FIX: linguist: solo en varios regiones hay: alternancia_vocálica: "e:ie"
    eludir:         {},
    embadurnar:     {},
    embarcar:       {},
    embestir:       { alternancia_vocálica: "e:i" },
    emborrachar:    {},
    emigrar:        {},
    emitir:         {},
    empacar:        {},
    empachar:       {},
    empapar:        {},
    emparejar:      {},
    empatar:        {},
    empeorar:       {},
    emperejilar:    {},
    emperifollar:   {},
    empezar:        { alternancia_vocálica: "e:ie" },
    emplear:        {},
    emprender:      {},
    empujar:        {},
    enamorar:       {},
    encajar:        {},
    encaminar:      {},
    encantar:       {},
    encaramar:      {},
    encargar:       {},
    encender:       { alternancia_vocálica: "e:ie" },
    encerrar:       { alternancia_vocálica: "e:ie" },
    enchufar:       {},
    encoger:        {},
    encomendar:     { alternancia_vocálica: "e:ie" },
    encontrar:      { alternancia_vocálica: "o:ue" },
    enderezar:      {},
    enfermar:       {},
    enflaquecer:    { tema_presente_yo_del_modelo: ["enflaquezc"]},
    enfrentar:      {},
    enfriar:        { modelo: "vaciar" },
    enfurecer:      { tema_presente_yo_del_modelo: ["enfurezc"] },
    engañar:        {},
    enganchar:      {},
    engordar:       {},
    enjugar:        { modelo: null},  // regular, no sigue el modelo de "jugar"
    enlazar:        {},
    enloquecer:     { tema_presente_yo_del_modelo: ["enloquezc"] },
    enmascarar:     {},
    enmendar:       { alternancia_vocálica: "e:ie" },
    enojar:         {},
    enraizar:       { modelo: "enraizar",
                        excepciones_léxicas: {
                            reglas: {
                                // FIX: lingüista: hay una regla por esta situación?
                                IndPres: { forms: { s1: ["enraízo"], s2: ["enraízas"], s3: ["enraíza"],                              p3: ["enraízan"]}},
                                SubPres: { forms: { s1: ["enraíce"], s2: ["enraíces"], s3: ["enraíce"],                              p3: ["enraícen"], vos: [{"forma":"enraíces","uso":"Riop."},{"forma":"enraicés","uso":"C.Am."}] }},
                                CmdPos:  { forms: { s2: ["enraíza"], s3: ["enraíce"],                                                p3: ["enraícen"]}}
                            },
                        }
                    },
    enredar:        {},
    enroscar:       {},
    ensamblar:      {},
    ensanchar:      {},
    enseñar:        {},
    ensuciar:       {},
    entender:       { alternancia_vocálica: "e:ie" },
    enterar:        {},
    enterrar:       { alternancia_vocálica: "e:ie" },
    entrar:         {},
    entrechocar:    {},
    entregar:       {},
    entrever:       { modelo: "ver" },
    entrevistar:    {},
    entristecer:    { tema_presente_yo_del_modelo: ["entristezc"] },
    entumecer:      { tema_presente_yo_del_modelo: ["entumezc"] },
    entusiasmar:    {},
    enviar:         { modelo: "vaciar" },
    envidiar:       {},
    envolver:       { modelo: "volver" },
    erguir:         { modelo: "erguir",
                        alternancia_vocálica: "e:ie",
                        tema_presente_yo_del_modelo: ["irg", "yerg"],
                        excepciones_léxicas: {
                            gerundio: ["irguiendo"],
                            reglas: {
                                // FIX: lingüista: hay una regla por esta situación?
                                IndPres: { forms: { s1: ["irgo", "yergo"],       s2: ["irgues", "yergues"], s3: ["irgue", "yergue"],
                                                                                                            p3: ["irguen", "yerguen"] }},
                                IndPret: { forms: {                                                         s3: ["irguió"],
                                                                                                            p3: ["irguieron"]} },
                                SubPres: { 
                                           // Según ChatGPT: hay un conflicto entre irregularidad heredada vs. regularización del voseo
                                           //    sí existe una forma voseante tipo yergás, pero en la práctica, muchas veces se dice ergás o se evita el verbo
                                           forms: { vos: [{"forma":"yergas","uso":"Riop."},{"forma":"irgas","uso":"C.Am."},{"forma":"irgás","uso":"C.Am."}] }
                                        //    forms: { s1: ["irga", "yerga"],       s2: ["irgas", "yergas"],   s3: ["irga", "yerga"],
                                        //             p1:	["irgamos", "yergamos"], p2: ["irgáis", "yergáis"], p3: ["irgan", "yergan"], vos: ["yergas"] }
                                                 },
                                SubImp: { tema: ["irguie"], stress_last_char_of_p1_stem: true },
                                SubFut: { tema: ["irguie"], stress_last_char_of_p1_stem: true },
                                CmdPos: { forms: {                               s2: ["irgue", "yergue"],   s3:	["irga", "yerga"],
                                                   p1: ["irgamos", "yergamos"],                             p3: ["irgan", "yergan"] }}
                            },
                        }
                    },
    errar:          {}, // FIX: tiene dos formas
    eructar:        {},
    escabullir:     {},
    escalar:        {},
    escanear:       {},
    escapar:        {},
    escoger:        {},
    esconder:       {},
    escribir:       { excepciones_léxicas: { participio: ["escrito"] } },
    escuchar:       {},
    esculpir:       {},
    esforzar:       { alternancia_vocálica: "o:ue" },
    espantar:       {},
    esparcir:       { tema_presente_yo_del_modelo: ["esparz"] },
    esperar:        {},
    espiar:         { modelo: "vaciar" },
    esquiar:        { modelo: "vaciar" },
    establecer:     { tema_presente_yo_del_modelo: ["establezc"] },
    estacionar:     {},
    estafar:        {},
    estandarizar:   {},
    estar:         { modelo: "estar",
                        auxiliar: true,
                        sufijo_presente_yo: "oy",
                        tema_pretérito_del_modelo: "estuv", 
                        excepciones_léxicas: {
                            imperativo_tú: ["está"],
                            reglas: {
                                IndPres: { suffixes: {            s2: ["ás"], s3: ["á"], p3: ["án"]}},
                                IndPret: { suffixes: { s1: ["e"], s2: ["iste"], s3: ["o"],  p1: ["imos"],   p2: ["isteis"], p3: ["ieron"] } },
                                SubPres: { suffixes: { s1: ["é"], s2: ["és"], s3: ["é"], p3: ["én"],        vos: null }},
                                CmdPos:  { suffixes: {                       s3: ["é"], p3: ["én"]}}
                            }
                        }
                    },
    estatuir:       {},
    estimar:        {},
    estipular:      {},
    estofar:        {},
    estornudar:     {},
    estrangular:    {},
    estrechar:      {},
    estregar:       { alternancia_vocálica: "e:ie" },  // FIX: multiple forms
    estremecer:     { tema_presente_yo_del_modelo: ["estremezc"] },
    estrenar:       {},
    estropear:      {},
    estudiar:       {},
    evadir:         {},
    evaluar:        {},
    evitar:         {},
    examinar:       {},
    exasperar:      {},
    exceder:        {},
    exceptuar:      {},
    excluir:        {},
    exhalar:        {},
    exigir:         {},
    existir:        {},
    expandir:       {},
    expedir:        { alternancia_vocálica: "e:i" },
    expiar:         { modelo: "vaciar" },
    explicar:       {},
    explorar:       {},
    exponer:        {},
    expresar:       {},
    extender:       { alternancia_vocálica: "e:ie" },
    extenuar:       {},
    extinguir:      {},
    extraer:        {},
    extrañar:       {},
    fabricar:       {},
    facilitar:      {},
    facturar:       {},
    fallar:         {},
    fallecer:       { tema_presente_yo_del_modelo: ["fallezc"]},
    faltar:         {},
    fascinar:       {},
    felicitar:      {},
    festejar:       {},
    figurar:        {},
    fijar:          {},
    finalizar:      {},
    fingir:         {},
    firmar:         {},
    flanquear:      {},
    flaquear:       {},
    flexionar:      {},
    flotar:         {},
    fluctuar:       {},
    fluir:          {},
    formar:         {},
    forzar:         { alternancia_vocálica: "o:ue" },
    fotografiar:    { modelo: "vaciar" },
    fraguar:        {},
    frecuentar:     {},
    fregar:         { alternancia_vocálica: "e:ie" },
    freír:          { modelo: "reír" },
    frotar:         {},
    fruncir:        { tema_presente_yo_del_modelo: ["frunz"] },
    fulgurar:       {},
    fumar:          {},
    funcionar:      {},
    fundir:         {},
    ganar:          {},
    gastar:         {},
    gemir:          { modelo: "pedir" },
    generar:        {},
    germinar:       {},
    girar:          {},
    gobernar:       { alternancia_vocálica: "e:ie" },
    gotear:         {},
    gozar:          {},
    grabar:         {},
    graduar:        {},
    granizar:       { defectos: {personas: ["s3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    gritar:         {},
    gruir:          {},
    gruñir:         {},
    guardar:        {},
    guiar:          { modelo: "guiar",
                        // clase_conjugacional: "-iar",
                        // TODO: hay formas reformadas en la reforma ortográfica de la RAE de 2010, considera añadir estas formas
                        // Otherwise, the accent is the only thing different from the regular forms
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { stress_last_vowel_of_s123p3_stem: true,
                                           forms:    {                                   p2: ["guiais",{"forma":"guiáis","uso":"pre-2010"}],
                                                                          vos: ["guias",{"forma":"guiás","uso":"pre-2010"}]   }},
                                IndPret: { forms:    { s1: ["guie",{"forma":"guié","uso":"pre-2010"}],          s3: ["guio",{"forma":"guió","uso":"pre-2010"}],  } },
                                SubPres: { stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true,
                                        forms: {                                        p2: ["guieis",{"forma":"guiéis","uso":"pre-2010"}] }},
                                CmdPos:  { stress_last_vowel_of_s123p3_stem: true,
                                        forms: {                                                               vos: ["guia"] }}
                            }
                        }
                    },
    guisar:         {},
    gustar:         {},
    haber:          { modelo: "haber",
                        tema_pretérito_del_modelo: "hub",
                        tema_futuro_del_modelo: "habr",
                        impersonal: true,
                        auxiliar: true,
                        excepciones_léxicas: {
                            supletivo: true,
                            imperativo_tú: [{"forma":"he","uso":"arcaico"},{"forma":"habe","uso":"arcaico"}],
                            reglas: {
                                IndPres: { forms: { s1: ["he"],     s2: ["has"],  s3: ["ha", {forma: "hay", uso: "impersonal"}],     
                                                    p1: ["hemos"],                p3: ["han"],   vos: null} },
                                SubPres: { tema: ["hay"] },
                                CmdPos:  { tema: ["hay"],
                                        forms: {                 p2: ["habed"] ,              vos: null } }
                            }
                        }
                    },
    habitar:        {},
    habituar:       {},
    hablar:         {},
    hacer:          { modelo: "hacer",
                        clase_conjugacional: "-acer",
                        tema_presente_yo_del_modelo: ["hag"],
                        tema_pretérito_del_modelo: "hic",
                        tema_futuro_del_modelo: "har",
                        excepciones_léxicas: {
                            participio: ["hecho"],
                            imperativo_tú: ["haz"],
                            reglas: {
                                // FIX: linguist: should "hizo" be managed with sound preserving transformations?
                                IndPret: { forms: {s3: ["hizo"]} },
                                SubPres: { forms: {vos: [{forma:"hagas",uso:"Riop."}, {forma:"hagás",uso:"C.Am."}]} },
                            }
                        }
                    },
    halar:          {},
    hallar:         {},
    hartar:         {},
    heder:          { alternancia_vocálica: "e:ie" },
    helar:          { alternancia_vocálica: "e:ie" },
    hendir:         { alternancia_vocálica: "e:ie" },  // but not the "e:i" for IndPret...
    herir:          { alternancia_vocálica: "e:ie" },
    herrar:         { alternancia_vocálica: "e:ie" },
    hervir:         { alternancia_vocálica: "e:ie" },
    hilvanar:       {},
    hornear:        {},
    hospedar:       {},
    huir:           { /* se conjuga de forma regular, solo hay reglas especiales de ortografía */ },
    humanizar:      {},
    humillar:       {},
    hundir:         {},
    identificar:    {},
    ignorar:        {},
    igualar:        {},
    iluminar:       {},
    imaginar:       {},
    imbuir:         {},
    impedir:        { alternancia_vocálica: "e:i" },
    implantar:      {},
    implorar:       {},
    imponer:        {},
    importar:       {},
    imposibilitar:  {},
    impregnar:      {},
    impresionar:    {},
    imprimir:       { 
                        excepciones_léxicas: { gerundio: ["imprimido","impreso"] } },
    inclinar:       {},
    incluir:        {},
    incrementar:    {},
    incrustar:      {},
    incubar:        {},
    indagar:        {},
    indexar:        {},
    indicar:        {},
    inferir:        { alternancia_vocálica: "e:ie" },
    infestar:       {},
    infligir:       {},
    influir:        {},
    informar:       {},
    infundir:       {},
    ingeniar:       {},
    ingerir:        { alternancia_vocálica: "e:ie" },
    ingresar:       {},
    inhalar:        {},
    iniciar:        {},
    injerir:        { alternancia_vocálica: "e:ie" },
    inmigrar:       {},
    inmiscuir:      {},
    inmunizar:      {},
    inquietar:      {},
    inquirir:       { alternancia_vocálica: "i:ie" },
    inscribir:      { excepciones_léxicas: { participio: ["inscrito"] } },
    insertar:       {},
    insinuar:       {},
    insistir:       {},
    inspeccionar:   {},
    instalar:       {},
    instar:         {},
    instituir:      {},
    instruir:       {},
    intentar:       {},
    interactuar:    {},
    intercalar:     {},
    intercambiar:   {},
    interesar:      {},
    interferir:     { alternancia_vocálica: "e:ie" },
    interpretar:    {},
    interrogar:     {},
    interrumpir:    {},
    intervenir:     { modelo: "venir" },
    intrigar:       {},
    introducir:     {},
    intuir:         { /* modelo: "huir" */ },
    inundar:        {},
    invadir:        {},
    invertir:       { alternancia_vocálica: "e:ie" },
    investir:       { alternancia_vocálica: "e:i" },
    invitar:        {},
    ir:             { modelo: "ir",
                        auxiliar: true,
                        no_admite_prefijos: true,
                        tema_pretérito_del_modelo: "fu",
                        sufijo_presente_yo: "oy",
                        excepciones_léxicas: {
                            supletivo: true,
                            participio: ["ido"],
                            gerundio: ["yendo"],
                            reglas: {
                                // The default "-ir" verb pattern of accent the last sylable doesn't apply to vos forms of "ir", since "ir" is only one sylable
                                IndPres: { forms: { s1: ["voy"], s2: ["vas"],    s3: ["va"],   p1: ["vamos"],  p2: ["vais"],     p3: ["van"], vos: null } },
                                SubPres: { tema: ["vay"],
                                        forms: {                                            vos: [{"forma":"vayas","uso":"Riop."},{"forma":"vayás","uso":"C.Am."}] }
                                },
                                IndPret: { forms: { s1: ["fui"], s2: ["fuiste"], s3: ["fue"],  p1: ["fuimos"], p2: ["fuisteis"], p3: ["fueron"] } },
                                IndImp:  { forms: { s1: ["iba"], s2: ["ibas"],   s3: ["iba"],  p1: ["íbamos"], p2: ["ibais"],    p3: ["iban"] } },
                                // IndFut: uses regular conjugation
                                // IndCond: uses regular conjugation
                                CmdPos:  { forms: {              s2: ["ve"],     s3: ["vaya"], p1: ["vayamos", "vamos"],         p3: ["vayan"], vos: ["andá"] } }
                            }
                        }
                    },
    irritar:        {},
    jactar:         {},
    jalar:          {},
    jubilar:        {},
    jugar: {
        // FIX: SubPres: vos spelling differs by region: vos: ["juegues", "*jugués"]
        alternancia_vocálica: "u:ue",
    },
    juntar:         {},
    jurar:          {},
    justificar:     {},
    juzgar:         {},
    lagrimear:      {},
    lamentar:       {},
    largar:         {},
    lastimar:       {},
    lavar:          {},
    leer:           { modelo: "leer", clase_conjugacional: "-eer" },
    levantar:       {},
    licenciar:      {},
    limpiar:        {},
    llamar:         {},
    llegar:         {},
    llenar:         {},
    llevar:         {},
    llorar:         {},
    llover:         { alternancia_vocálica: "o:ue", defectos: {personas: ["s3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },

    localizar:      {},
    lograr:         {},
    luchar:         {},
    lucir:          {},
    lustrar:        {},
    maldecir:       { modelo: "decir" },
    malgastar:      {},
    malquerer:      { modelo: "querer" },
    mandar:         {},
    manejar:        {},
    maniatar:       {},
    manifestar:     { alternancia_vocálica: "e:ie" },
    mantener:       {},
    maquillar:      {},
    marcar:         {},
    marchar:        {},
    martillar:      {},
    matar:          {},
    matchear:       {},
    maullar:        {},
    mecer:          {},
    medir:          { alternancia_vocálica: "e:i" },
    meditar:        {},
    mejorar:        {},
    mencionar:      {},
    mendigar:       {},
    menguar:        {},
    menstruar:      {},
    mentar:         { alternancia_vocálica: "e:ie" },
    mentir:         { alternancia_vocálica: "e:ie" },
    merecer:        { tema_presente_yo_del_modelo: ["merezc"] },
    merendar:       { alternancia_vocálica: "e:ie" },
    meter:          {},
    mirar:          {},
    modelar:        {},
    modernizar:     {},
    molestar:       {},
    montar:         {},
    morder:         { alternancia_vocálica: "o:ue" },
    morir:          { alternancia_vocálica: "o:ue" },
    mostrar:        { alternancia_vocálica: "o:ue" },
    mover:          { modelo: "mover", alternancia_vocálica: "o:ue" },
    mudar:          {},
    multiplicar:    {},
    murmurar:       {},
    nacer:          { tema_presente_yo_del_modelo: ["nazc"] },
    nadar:          {},
    necesitar:      {},
    negar:          { alternancia_vocálica: "e:ie" },
    nevar:          { alternancia_vocálica: "e:ie", defectos: {personas: ["s3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    nombrar:        {},
    notar:          {},
    nutrir:         {},
    obedecer:       { tema_presente_yo_del_modelo: ["obedezc"] },
    obligar:        {},
    observar:       {},
    obstruir:       {},
    obtener:        { modelo: "tener" },
    ocasionar:      {},
    ocluir:         {},
    ocupar:         {},
    ocurrir:        {},
    odiar:          {},
    ofrecer:        { tema_presente_yo_del_modelo: ["ofrezc"] },
    ofuscar:        {},
    oír:            { modelo: "oír",    // FIX: linguist: why is this a class?
                        tema_presente_yo_del_modelo: ["oig"],
                        excepciones_léxicas: {
                            reglas: {
                                CmdPos:  { suffixes: {                                                      p2: ["íd"],          } }
                            }
                        }
                    },
    oler:           { alternancia_vocálica: "o:ue" },
    olvidar:        {},
    operar:         {},
    oponer:         { modelo: "poner"},
    organizar:      {},
    originar:       {},
    orinar:         {},
    padecer:        { tema_presente_yo_del_modelo: ["padezc"] },
    pagar:          {},
    parar:          {},
    parecer:        { tema_presente_yo_del_modelo: ["parezc"] },
    parpadear:      {},
    participar:     {},
    partir:         {},
    partyar:        {},
    pasar:          {},
    pasear:         {},
    pasmar:         {},
    patinar:        {},
    patrullar:      {},
    pausar:         {},
    pedalear:       {},
    pedir:          { modelo: "pedir", 
                      alternancia_vocálica: "e:i",
                    //   excepciones_léxicas: {
                    //         reglas: {
                    //             SubPres: { 
                    //                 suffixes: { vos: [{"forma":"as","uso":"Riop."},{"forma":"ás","uso":"C.Am."}] }
                    //             }
                    //         }
                    //     }
                    },
    pegar:          {},
    peinar:         {},
    penetrar:       {},
    pensar:         { alternancia_vocálica: "e:ie",
                      excepciones_léxicas: {
                            reglas: {
                                SubPres: { forms: { vos: [{"forma":"pienses","uso":"Riop."},{"forma":"pensés","uso":"C.Am."}] }}
                            }
                        }
                    },
    perder:         { alternancia_vocálica: "e:ie" },
    perforar:       {},
    permanecer:     { tema_presente_yo_del_modelo: ["permanezc"] },
    permitir:       {},
    perpetrar:      {},
    perpetuar:      {},
    perseguir:      { alternancia_vocálica: "e:i" },
    pertenecer:     { tema_presente_yo_del_modelo: ["pertenezc"] },
    pervertir:      { alternancia_vocálica: "e:ie" },
    pesar:          {},
    pescar:         {},
    pestañear:      {},
    petrificar:     {},
    piar:           { modelo: "vaciar" },
    picar:          {},
    picotear:       {},
    pintar:         {},
    pisar:          {},
    planchar:       {},
    plasmar:        {},
    platicar:       {},
    plegar:         { alternancia_vocálica: "e:ie" },
    poblar:         { alternancia_vocálica: "o:ue" },
    poder:          { modelo: "poder",
                        auxiliar: true,
                        alternancia_vocálica: "o:ue",
                        tema_pretérito_del_modelo: "pud",
                        tema_futuro_del_modelo: "podr",
                        excepciones_léxicas: { gerundio_tema_cambio_excepcional: "o:u" }
                    },
    poner:          { modelo: "poner",
                        tema_presente_yo_del_modelo: ["pong"],
                        tema_pretérito_del_modelo: "pus",
                        tema_futuro_del_modelo: "pondr",
                        excepciones_léxicas: {
                            participio: ["puesto"],
                            imperativo_tú: ["pon"],
                            reglas: {
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    pordiosear:     {},
    portar:         {},
    posar:          {},
    poseer:         {},
    practicar:      {},
    precluir:       {},
    preferir:       { alternancia_vocálica: "e:ie" },
    preguntar:      {},
    prender:        {},
    preocupar:      {},
    preparar:       {},
    presenciar:     {},
    presentar:      {},
    presentir:      { alternancia_vocálica: "e:ie" },
    presionar:      {},
    prestar:        {},
    pretender:      {},
    prevenir:       { modelo: "venir" },
    prever:         { modelo: "ver" },
    principiar:     {},
    probar:         { alternancia_vocálica: "o:ue" },
    proceder:       {},
    procesar:       {},
    procurar:       {},
    producir:       {},
    proferir:       { alternancia_vocálica: "e:ie" },
    prohibir:       {},
    prohijar:       {},
    proliferar:     {},
    prometer:       {},
    promover:       { alternancia_vocálica: "o:ue" },
    pronunciar:     {},
    proponer:       {},
    proporcionar:   {},
    propugnar:      {},
    proseguir:      { alternancia_vocálica: "e:i" },
    prostituir:     {},
    proteger:       {},
    proveer:        {},   // tiene dos participios
    provenir:       { modelo: "venir" },
    provocar:       {},
    publicar:       {},
    pudrir:         { excepciones_léxicas: { participio: ["podrido"] } },
    pulir:          {},
    puntuar:        {},
    quebrantar:     {},
    quebrar:        { alternancia_vocálica: "e:ie" },
    quedar:         {},
    quejar:         {},
    quemar:         {},
    querer:         { modelo: "querer",
                        tema_pretérito_del_modelo: "quis",
                        tema_futuro_del_modelo: "querr",
                        alternancia_vocálica: "e:ie"
                    },
    quitar:         {},
    ramificar:      {},
    raspar:         {},
    rastrear:       {},
    realizar:       {},
    reanudar:       {},
    rebanar:        {},
    rebelar:        {},
    recetar:        {},
    rechazar:       {},
    rechinar:       {},
    recibir:        {},
    reciclar:       {},
    reclamar:       {},
    recluir:        {},
    recobrar:       {},
    recoger:        {},
    recolectar:     {},
    recomendar:     { alternancia_vocálica: "e:ie" },
    recomenzar:     { alternancia_vocálica: "e:ie" },
    reconfortar:    {},
    reconocer:      { modelo: "conocer" },
    reconstituir:   {},
    reconstruir:    {},
    recontar:       { alternancia_vocálica: "o:ue" },
    reconvenir:     { modelo: "venir" },
    recordar:       { alternancia_vocálica: "o:ue" },
    recorrer:       {},
    recuperar:      {},
    recurrir:       {},
    redistribuir:   {},
    redituar:       {},
    reducir:        {},
    reemplazar:     {},
    reencontrar:    { alternancia_vocálica: "o:ue" },
    reenviar:       { modelo: "vaciar" },
    reevaluar:      {},
    referir:        { alternancia_vocálica: "e:ie" },
    refluir:        {},
    reformar:       {},
    reforzar:       { alternancia_vocálica: "o:ue" },
    refugiar:       {},
    refutar:        {},
    regalar:        {},
    regañar:        {},
    regar:          { alternancia_vocálica: "e:ie" },
    regir:          { alternancia_vocálica: "e:i" },
    registrar:      {},
    regresar:       {},
    regular:        {},
    rehilar:        {},
    rehogar:        {},
    rehuir:         {},
    rehusar:        {},
    reinstalar:     {},
    reír:           { modelo: "reír",
                        alternancia_vocálica: "e:í",
                        excepciones_léxicas: {
                            gerundio: ["riendo"],
                            participio: ["reído"],
                            reglas: {
                                // FIX: linguist: are there other reglas I can use?
                                // FIX: bring in alternate forms
                                // FIX: must formalize the relationship of CmdPos on SubPres
                                IndPres: { stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true,
                                    // FIX: considera un campo "formas_adicionales", para que no tengamos repetir la forma que no cambia
                                    // FIX: es posible que podamos usar una regla de ortografía (rompe el diptongo) por el resto?
                                           forms: {s1: ["río"], /* s2: ["ríes"], s3: ["ríe"],*/ p1: ["reímos"], p2: ["reís"],  /*p3: ["ríen"],   vos: ["reís"], */}},
                                IndPret: { forms: {                           s3: ["rio",{"forma":"rió","uso":"pre-2010"}],                               /* p3: ["rieron"],*/} },
                                SubPres: { tema: ["rí"], stress_last_vowel_of_s123p3_stem: true,
                                           forms: {                          p1: ["riamos"], p2: ["riais",{"forma":"riáis","uso":"pre-2010"}], /*p3: ["rían"]*/ }},
                                CmdPos:  { tema: ["rí"],
                                           forms: {                                        p1: ["riamos"], p2: ["reíd"],                  vos: ["reí"]}}
                            },
                        }
                    },
    relajar:        {},
    relucir:        {},
    rememorar:      {},
    remendar:       { alternancia_vocálica: "e:ie" },
    remodelar:      {},
    remorder:       { alternancia_vocálica: "o:ue" },
    remover:        { alternancia_vocálica: "o:ue" },
    remplazar:      {},
    rendir:         { modelo: "pedir" },
    reñir:          { alternancia_vocálica: "e:i" },
    renovar:        { alternancia_vocálica: "o:ue" },
    renunciar:      {},
    reparar:        {},
    repartir:       {},
    repasar:        {},
    repercutir:     {},
    repetir:        { alternancia_vocálica: "e:i" },
    replicar:       {},
    reposar:        {},
    representar:    {},
    reprimir:       {},
    reprobar:       { alternancia_vocálica: "o:ue" },
    requerir:       { alternancia_vocálica: "e:ie" },
    resbalar:       {},
    resentir:       { alternancia_vocálica: "e:ie" },
    resfriar:       { modelo: "vaciar" },
    resistir:       {},
    resolver:       { modelo: "mover" },
    respetar:       {},
    respirar:       {},
    responder:      {},
    restar:         {},
    restaurar:      {},
    restituir:      {},
    restringir:     {},
    resultar:       {},
    retener:        { modelo: "tener" },
    retornar:       {},
    retozar:        {},
    retribuir:      {},
    retumbar:       {},
    reunir:         { alternancia_vocálica: "u:ú" },
    revaluar:       {},
    revelar:        {},
    reventar:       { alternancia_vocálica: "e:ie" },
    revertir:       { alternancia_vocálica: "e:ie" },
    revisar:        {},
    revolver:       { modelo: "volver" },
    rezagar:        {},
    rimar:          {},
    robar:          {},
    rociar:         { modelo: "vaciar" },
    rodar:          { alternancia_vocálica: "o:ue" },
    rogar:          { alternancia_vocálica: "o:ue" },
    romper:         { excepciones_léxicas: { participio: ["roto"] } },
    rondar:         {},
    saber:          { modelo: "saber",
                        tema_pretérito_del_modelo: "sup",
                        tema_futuro_del_modelo: "sabr",
                        excepciones_léxicas: {
                            reglas: {
                                // similar a caber
                                IndPres: { forms: { s1: ["sé"] } },
                                SubPres: { tema: ["sep"] },
                                CmdPos:  { forms: {                                s3: ["sepa"],  p1: ["sepamos"],                     p3: ["sepan"] } }
                            }
                        }
                    },
    saborear:       {},
    sacar:          {},
    saciar:         {},
    sacudir:        {},
    sahumar:        {},
    salir:          { modelo: "salir",
                        tema_presente_yo_del_modelo: ["salg"],
                        tema_futuro_del_modelo: "saldr",
                        excepciones_léxicas: { imperativo_tú: ["sal"] }
                    },
    salpimentar:    { alternancia_vocálica: "e:ie" },
    saludar:        {},
    santiguar:      {},
    satisfacer:     { modelo: "hacer" },
    secar:          {},
    seducir:        {},
    seguir:         {
                        // NOTE: this does not conjugate as a "-uir" clase infinitivo
                        tema_presente_yo_del_modelo: ["sig"],
                        alternancia_vocálica: "e:i",
                    },
    seleccionar:    {},
    sellar:         {},
    sembrar:        { alternancia_vocálica: "e:ie" },
    sentar:         { alternancia_vocálica: "e:ie" },
    sentir:         { alternancia_vocálica: "e:ie" },
    separar:        {},
    ser:            { modelo: "ser",
                        auxiliar: true,
                        no_admite_prefijos: true,
                        tema_pretérito_del_modelo: "fu",
                        excepciones_léxicas: {
                            supletivo: true,
                            reglas: {
                                IndPres: { forms: { s1: ["soy"], s2: ["eres"],   s3: ["es"],    p1: ["somos"],  p2: ["sois"],     p3: ["son"],    vos: ["sos"] } },
                                IndImp:  { forms: { s1: ["era"], s2: ["eras"],   s3: ["era"],   p1: ["éramos"], p2: ["erais"],    p3: ["eran"]}},
                                IndPret: { forms: { s1: ["fui"], s2: ["fuiste"], s3: ["fue"],   p1: ["fuimos"], p2: ["fuisteis"], p3: ["fueron"] } },
                                SubPres: { tema: ["se"],
                                        forms: {                                             vos: [{"forma":"seas","uso":"Riop."},{"forma":"seás","uso":"C.Am."}] }},
                                CmdPos:  { forms: {              s2: ["sé"],     s3: ["sea"],   p1: ["seamos"],                   p3: ["sean"],   vos: null} }
                            }
                        }
                    },
    serrar:         { alternancia_vocálica: "e:ie" },
    servir:         { alternancia_vocálica: "e:i" },
    sesgar:         {},
    significar:     {},
    simplificar:    {},
    situar:         {},
    sobrecargar:    {},
    sobrecoger:     {},
    sobrehilar:     {},
    sobresalir:     {},
    sobrevenir:     { modelo: "venir" },
    sobrevivir:     {},
    sofreír:        { modelo: "reír" },
    solar:          { alternancia_vocálica: "o:ue" },
    soldar:         { alternancia_vocálica: "o:ue" },
    soler:          { alternancia_vocálica: "o:ue" },
    solicitar:      {},
    sollozar:       {},
    soltar:         { alternancia_vocálica: "o:ue" },
    solucionar:     {},
    someter:        {},
    sonar:          { alternancia_vocálica: "o:ue" },
    soñar:          { alternancia_vocálica: "o:ue" },
    sonreír:        { modelo: "reír" },
    soportar:       {},
    sorprender:     {},
    sortear:        {},
    sosegar:        { alternancia_vocálica: "e:ie" },
    sospechar:      {},
    sostener:       {},
    soterrar:       {},
    subir:          {},
    substituir:     {},
    substraer:      {},
    subvenir:       { modelo: "venir" },
    subvertir:      { alternancia_vocálica: "e:ie" },
    succionar:      {},
    suceder:        {},
    sudar:          {},
    sufrir:         {},
    sugerir:        { alternancia_vocálica: "e:ie" },
    sujetar:        {},
    suministrar:    {},
    suplicar:       {},
    suponer:        {},
    supurar:        {},
    surgir:         {},
    suscribir:      { excepciones_léxicas: { participio: ["suscrito"] } },
    suspender:      {},
    suspirar:       {},
    sustentar:      {},
    sustituir:      {},
    sustraer:       {},
    tallar:         {},
    tañer:          {},
    tapar:          {},
    tapiar:         {},
    tardar:         {},
    tartamudear:    {},
    tatuar:         {},
    temblar:        { alternancia_vocálica: "e:ie" },
    temer:          {},
    tender:         { alternancia_vocálica: "e:ie" },
    tener:          { modelo: "tener", 
                        auxiliar: true,
                        tema_presente_yo_del_modelo: ["teng"],
                        tema_pretérito_del_modelo: "tuv",
                        tema_futuro_del_modelo: "tendr",
                        alternancia_vocálica: "e:ie",
                        excepciones_léxicas: {
                            imperativo_tú: ["ten"],
                            reglas: {
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    teñir:          { alternancia_vocálica: "e:i" },
    tentar:         { alternancia_vocálica: "e:ie" },
    terminar:       {},
    textear:        {},
    tipificar:      {},
    tirar:          {},
    titubear:       {},
    tocar:          {},
    tolerar:        {},
    tomar:          {},
    torcer:         { alternancia_vocálica: "o:ue", tema_presente_yo_del_modelo: ["tuerz"] },
    tornar:         {},
    toser:          {},
    tostar:         { alternancia_vocálica: "o:ue" },
    trabajar:       {},
    traducir:       {},
    traer:          { modelo: "traer", tema_presente_yo_del_modelo: ["traig"], tema_pretérito_del_modelo: "traj" },
    transcender:    { alternancia_vocálica: "e:ie" },
    transcurrir:    {},
    transferir:     { alternancia_vocálica: "e:ie" },
    transformar:    {},
    transmitir:     {},
    transportar:    {},
    trapear:        {},
    trascender:     { alternancia_vocálica: "e:ie" },
    trasferir:      { alternancia_vocálica: "e:ie" },
    traspasar:      {},
    trastabillar:   {},
    tratar:         {},
    trepar:         {},
    triangular:     {},
    triturar:       {},
    trocar:         { alternancia_vocálica: "o:ue" },
    tronar:         { alternancia_vocálica: "o:ue", defectos: {personas: ["s3"], rasgos: ["IndPres", "IndImp", "IndPret", "IndFut", "IndCond", "SubPres" , "SubImp" , "SubFut"]} },
    tropezar:       { alternancia_vocálica: "e:ie" },
    tumbar:         {},
    turnar:         {},
    ubicar:         {},
    unir:           {},
    urgir:          {},
    usar:           {},
    utilizar:       {},
    vaciar:         { modelo: "vaciar",
                        clase_conjugacional: "-iar",
                        // FIX: linguist: The accent is the only thing different from the regular forms
                        // Is this due to an orthographic rule? or something else?
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { stress_last_vowel_of_s123p3_stem: true },
                                SubPres: { stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true },
                                CmdPos:  { stress_last_vowel_of_s123p3_stem: true }
                            }
                        }
                    },
    vacilar:        {},
    valer:          { tema_presente_yo_del_modelo: ["valg"], tema_futuro_del_modelo: "valdr" },
    validar:        {},
    valuar:         {},
    variar:         { modelo: "vaciar" },
    velar:          {},
    vencer:         { tema_presente_yo_del_modelo: ["venz"]},
    vender:         {},
    venir:          { modelo: "venir",
                        tema_presente_yo_del_modelo: ["veng"],
                        tema_pretérito_del_modelo: "vin",
                        tema_futuro_del_modelo: "vendr",
                        alternancia_vocálica: "e:ie",
                        excepciones_léxicas: {
                            gerundio: ["viniendo"],
                            imperativo_tú: ["ven"],
                            reglas: {
                                SubPres: {forms: {vos:[{"forma":"vengas","uso":"Riop."},{"forma":"vengás","uso":"C.Am."}] }},
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    ver:            { modelo: "ver",
                        // parece que no conforma bien a estas reglas
                        // sí prefijo_ind_pres_yo cambia, pero no con "g", y no con los mismos cambios
                        // no aplican ni tema_pretérito_del_modelo ni tema_futuro_del_modelo ni alternancia_vocálica
                        // el resto son excepciones_léxicas
                        excepciones_léxicas: {
                            gerundio: ["viendo"],
                            participio: ["visto"],
                            // hay varias excepciones_léxicas que probablemente tienen que ver con el hecho que ver es solo una sílaba
                            reglas: {
                                // p2 => accent dropped
                                // The default "-er" verb pattern of accent the last sylable doesn't apply to vos forms of "ver", since "vés" is only one sylable
                                IndPres: { suffixes: { s1: ["eo"],                                              p2: ["eis"],                        vos: null },
                                           derivations: {preserve_stress_from_base: ["s2","s3","p2","p3"]}
                                        },
                                SubPres: { tema: ["ve"] },
                                // accents dropped
                                IndPret: { forms: { s1: ["vi"], s3: ["vio"] },
                                           derivations: {preserve_stress_from_base: ["s1", "s3"]}
                                        },
                                IndImp: { tema: ["ve" ]},
                                CmdPos: { forms: {                      s3: ["vea"],           p1: ["veamos"],               p3: ["vean"],            vos: null },
                                          derivations: {preserve_stress_from_base: ["s2"] }
                                        }
                            }
                        }
                    },
    verraquear:     {},
    verter:         { alternancia_vocálica: "e:ie" },
    vestir:         { alternancia_vocálica: "e:i" },
    viajar:         {},
    vidriar:        { modelo: "vaciar" },
    vigilar:        {},
    violar:         {},
    virar:          {},
    visitar:        {},
    vivir:          {},
    volar:          { alternancia_vocálica: "o:ue"},
    volcar:         { alternancia_vocálica: "o:ue" },
    voltear:        {},
    volver:         { modelo: "volver", alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["vuelto"] } },
    votar:          {},
    xerografiar:    { modelo: "vaciar" },
    yacer:          {},   // FIX: { tema_presente_yo_del_modelo: ["yazc", "yazg", "yag"] },
    zaherir:        { alternancia_vocálica: "e:ie" },
    zambuir:        {},
    zambullir:      {},
    zampar:         {},
    zumbar:         {},
}


export function getAnnotations(infinitivo: string, modelo: ModeloConjugacional, mood_tense_derivation: ConjugationOrDerivation) : VerbConjugationAnnotation {
    const annotations: VerbConjugationAnnotation = {infinitivo, mood_tense_derivation, modelo, version, license}
    return annotations
}
