import { GrammaticalPerson, StemChangeRuleId, MoodTense, MoodTenseMap, VerbConjugation, VerbConjugationAnnotation, VerbConjugationChanges, ConjugationOrDerivation, Participios, FormaConjugada, Defectos, PersonasGramaticalesConVos, StemChangeFamily, IrregularYRegular } from "."
import { FailedTests } from "../test"
import { VerbAspectModifications } from "./regular-verb-rules"
import { version } from "./version.js"
import { license } from "./licencia.js"



export type InfinitiveClass = "-ar" | "-er" | "-ir"

// A family of verbs that conjugate the same depending on the termination.
// These start with a preceding hyphen to emphasize that the form is not a verb itself.
// However, this doesn't mean that all verbs with this termination conjugate the same way, 
// for example, the model for "-iar" is "vaciar", but "estudiar" is regular. 
// "-eír": comes from desleír, which is conjugated like "reír"
export type VerboClaseConjugacional = "-acer" | "-ducir" | "-eer" | "-eír" | "-iar" | "-uir"


// El modelo de la conjugación.
// Para verbos regulares, no especifica un modelo.
// Es posibile que el modelo de "maldecir" deba ser "bendecir"
export type ModeloConjugacional = 
        | "delinquir"
        | "andar"    | "caber"    | "caer"     | "cernir"   | "conducir" | "conocer"
        | "dar"      | "decir"    | "dormir"   | "enraizar" | "erguir"   | "estar"
        | "guiar"    | "haber"    | "hacer"    | "ir"       | "jugar"    | "leer"     | "lucir"
        | "maldecir" | "mover"    | "oír"      | "pedir"    | "placer"   | "poder"    | "poner"    | "querer"
        | "reír"     | "roer"     | "saber"    | "salir"    | "seguir"   | "ser"
        | "tener"    | "traer"    | "vaciar"   | "valer"    | "venir"    | "ver"      | "volver"


// The rules for conjugating a single form of an irregular verb, such as: "IndPres", "IndImp"
export interface VerbAspectRulesWithFullyIrregularForms extends VerbAspectModifications {
    // morphology
    suffixes?: VerbConjugationChanges
    // suplication
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    tema_suplicativo?: FormaConjugada[]
    temas?: VerbConjugation
    forms?: VerbConjugation
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    derivations?: {
        preserve_stress_from_base?: GrammaticalPerson[]
    }
}


export interface ReglasDeConjugaciónDeVerboExcepcionesLexicas extends Participios<FormaConjugada[]> {
    // irregulares como: "ir", "ser"
    supletivo?: true,
    // Solo para casos irregulares, sí para "poder", no para "dormir"
    gerundio_tema_cambio_excepcional?: StemChangeRuleId
    // solo por los verbos de modelos, o sea, ModeloConjugacional's
    imperativo_tú?: FormaConjugada[]
    tema_subjuntivo_yo?: string
    // FIX: narrow this type for exceptions, e.g. disallow add_suffix_to_infinitive
    reglas?: MoodTenseMap<VerbAspectRulesWithFullyIrregularForms>
}

// Hay dos categorías: verbos que admiten personificación, y los que están retringidos gramaticalmente.
// La categoría determina como puede conjugarlo.
// Los "naturales" lleva la conjugación completa, pero normalmente solo usa la forma de tersera persona singular, y no hay formas de mandatos.
// Los "gramaticales"lleva una conjugación parcial, porque nunca permiten el uso de otras formas
// Usa las formas de tersera persona singular y tersera persona plural, y no hay formas de mandatos.
// "soler" es único.
export type Impersonal = "natural" | "gramatical" | "soler"

// true means all tests passed, otherwise FailedTests lists the correct results for each failed test.
export type TestResults = true | FailedTests

// FIX: want to explain reason/origin/etemology for each change... this could help learners
export interface ReglasDeConjugaciónDeVerbo {
    // Used only by resolveConjugationClass(), to associate each portion of a collection of rules with the verb to which they apply.
    // These are ordered from most specific (the original infinitivo), to the most basic. Normally there are only one or two.
    // For example: ["retener", "tener"]
    infinitivos?: string[]
    // null is used to override a model in a base verb, or a verb tht might appear to be a base. e.g. "conjugar"
    modelo?: ModeloConjugacional | null
    clase_conjugacional?: VerboClaseConjugacional
    no_admite_prefijos?: true
    auxiliar?: true
    // Si el uso del verbo está retringido por defecto.
    impersonal?: Impersonal
    // Hay verbos con formas multiples como erguir
    tema_presente_yo_del_modelo?: FormaConjugada[]
    // FIX: lingüista: Cuáles son las diferencias entre esto y excepciones_léxicas de sufijo?
    // dar -> 'd' + '-oy'
    // solo existe por modelos
    sufijo_presente_yo?: string
    tema_pretérito_del_modelo?: string
    // tema especial del futuro / condicional
    // This may only be specified for verb models.
    // FIX: try to improve type system to prevent setting this on non-model
    tema_futuro_del_modelo?: string
    alternancia_vocálica?: StemChangeFamily
    // La alternancia_vocálica produce un hiato, no un diptongo,
    // FIX: También es posible que haya una restricción adicional: solo lo marca en sílabas tónicas
    ponga_hiato?: true
    // Propiedades que no se generalizan bien, no productivos, no extrapolable.
    excepciones_léxicas?: ReglasDeConjugaciónDeVerboExcepcionesLexicas
    // El verbo tiene dos formas: la de este descripción y la regular. p. ej. ""asolar""
    acepta_regular?: IrregularYRegular
    // Inidica que las pruebas pasan, o cuáles son los errores.
    // El app de web usa estos resultados para presentar las formas correctas al usuario.
    ok?: TestResults
}


// if a value is null, the verb is regular
// A verb that appears in this list has been verified with a test
export const verbos_con_cambios_morfológicos : {[infinitivo: string]: ReglasDeConjugaciónDeVerbo} = {
    abandonar:      {},
    abatir:         {},
    abolir:         {},    // FIX: abolir no se conjuga como abolo, aboles, abola, etc. Se usan perífrasis: va a abolir
    abrasar:        {},
    abrazar:        {},
    abreviar:       {},
    abrir:          { excepciones_léxicas: { participio: ["abierto"] } },
    abrumar:        {},
    absolver:       { alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["absuelto"] } },
    absorber:       {},
    abstener:       { modelo: "tener" },
    abundar:        {},
    aburrir:        {},
    acabar:         { auxiliar: true },
    acaecer:        { impersonal: "gramatical" },
    acampar:        {},
    acarrear:       {},
    acceder:        {},
    acechar:        {},
    acelerar:       {},
    acentuar:       {},
    aceptar:        {},
    acercar:        {},
    acertar:        { alternancia_vocálica: "e:ie" },
    achicar:        {},
    acicalar:       {},
    acoger:         {},
    acometer:       {},
    acompañar:      {},
    acongojar:      {},
    aconsejar:      {},
    acontecer:      { impersonal: "gramatical" },
    acordar:        { alternancia_vocálica: "o:ue" },
    acostar:        { alternancia_vocálica: "o:ue" },
    acreditar:      {},
    actualizar:     {},
    actuar:         {},
    acudir:         {},
    acumular:       {},
    acusar:         {},
    adaptar:        {},
    adelgazar:      {},
    adherir:        { alternancia_vocálica: "e:ie" },
    adicionar:      {},
    adjuntar:       {},
    adobar:         {},
    adquirir:       { alternancia_vocálica: "i:ie",
                      excepciones_léxicas: {
                            reglas: {
                                // FIX: try to use temas instead
                                SubPres: { forms: { vos: [{"forma":"adquier/as","uso":"Riop."},{"forma":"adquir/ás","uso":"C.Am."}]    }},
                            }
                        }     
                    },
    adueñar:        {},
    advenir:        { modelo: "venir" },
    advertir:       { alternancia_vocálica: "e:ie" },
    afectar:        {},
    afeitar:        {},
    aferrar:        {},
    afirmar:        {},
    afligir:        {},
    aflojar:        {},
    aflorar:        {},
    afluir:         {},
    agachar:        {},
    agarrar:        {},
    agasajar:       {},
    agitar:         {},
    agolpar:        {},
    agradar:        {},
    agradecer:      {},
    agravar:        {},
    agredir:        {},   // FIX: Similar a abolir: falta presente de indicativo (excepto agredimos, agredís)
    agregar:        {},
    agrupar:        {},
    aguantar:       {},
    aguar:          {},
    agudizar:       {},
    ahijar:         {},
    ahitar:         {},
    ahorrar:        {},
    ahusar:         {},
    ahuyentar:      {},
    airar:          {},
    aislar:         {},
    ajustar:        {},
    alargar:        {},
    alarmar:        {},
    albergar:       {},
    alcanzar:       {},
    alcoholizar:    {},
    alegrar:        {},
    alejar:         {},
    alentar:        { alternancia_vocálica: "e:ie" },
    aliar:          { modelo: "vaciar" },
    alimentar:      {},
    aliviar:        {},
    almorzar:       { alternancia_vocálica: "o:ue" },
    alocar:         {},
    alojar:         {},
    alquilar:       {},
    // alquiler:    no es un verbo según el DEL de la RAE
    alterar:        {},
    alucinar:       {},
    alumbrar:       {},
    amaestrar:      {},
    amalgamar:      {},
    amanecer:       { impersonal: "natural" },
    amar:           {},
    amarrar:        {},
    amasar:         {},
    amnistiar:      { modelo: "vaciar" },
    amohinar:       {},
    amortiguar:     {},
    amparar:        {},
    ampliar:        { modelo: "vaciar" },
    añadir:         {},
    anclar:         {},
    andar:          { modelo: "andar",
                        auxiliar: true, 
                        tema_pretérito_del_modelo: "anduv",
                        excepciones_léxicas: {
                            reglas: {
                                IndPret: { suffixes: {                                  p3: ["ieron"]}},
                            }
                        }
                    },
    anhelar:        {},
    anidar:         {},
    animar:         {},
    aniquilar:      {},
    anochecer:      { impersonal: "natural" },
    anotar:         {},
    ansiar:         { modelo: "vaciar" },
    anticuar:       {},
    anudar:         {},
    anunciar:       {},
    apacentar:      { alternancia_vocálica: "e:ie" },
    apaciguar:      {},
    apagar:         {},
    aparar:         {},
    aparcar:        {},
    aparecer:       {},
    apartar:        {},
    apercibir:      {},
    apetecer:       {},
    aplastar:       {},
    aplaudir:       {},
    aplicar:        {},
    apoderar:       {},
    apostar:        { alternancia_vocálica: "o:ue" },
    apreciar:       {},
    aprehender:     {},
    aprender:       {},
    apresar:        {},
    apresurar:      {},
    apretar:        { alternancia_vocálica: "e:ie" },
    aprobar:        { alternancia_vocálica: "o:ue" },
    aprovechar:     {},
    apuñalar:       {},
    apuntalar:      {},
    apuntar:        {},
    apurar:         {},
    aquilatar:      {},
    argüir:         {},
    argumentar:     {},
    armar:          {},
    arraigar:       {},
    arrancar:       {},
    arrasar:        {},
    arrastrar:      {},
    arreglar:       {},
    arremeter:      {},
    arrendar:       { alternancia_vocálica: "e:ie" },
    arrepentir:     { alternancia_vocálica: "e:ie" },
    arribar:        {},
    arriesgar:      {},
    arrimar:        {},
    arrojar:        {},
    arropar:        {},
    arrugar:        {},
    arruinar:       {},
    arrullar:       {},
    asaltar:        {},
    ascender:       { alternancia_vocálica: "e:ie" },
    asegurar:       {},
    asentar:        { alternancia_vocálica: "e:ie" },
    asentir:        { alternancia_vocálica: "e:ie" },
    asesinar:       {},
    asignar:        {},
    asir:           { tema_presente_yo_del_modelo: ["asg"] },
    asistir:        {},
    asolar:         { alternancia_vocálica: "o:ue", acepta_regular: "variante" },
    asolear:        {},
    asomar:         {},
    asombrar:       {},
    aspirar:        {},
    asustar:        {},
    atajar:         {},
    atañer:         { impersonal: "gramatical" },
    atar:           {},
    atardecer:      { impersonal: "natural" },
    atemorizar:     {},
    atender:        { alternancia_vocálica: "e:ie" },
    atenuar:        {},
    aterir:         {},   // FIX: Solo se usa en formas donde la raíz no lleva "i" tónica: atería, aterido; No se usa atero, ateres
    atestiguar:     {},
    atiborrar:      {},
    atinar:         {},
    atorar:         {},
    atormentar:     {},
    atornillar:     {},
    atraer:         { modelo: "traer" },
    atravesar:      { alternancia_vocálica: "e:ie" },
    atrever:        {},
    atribuir:       {},
    atropellar:     {},
    aullar:         {},
    aumentar:       {},
    aunar:          {},
    aupar:          {},
    auscultar:      {},
    autoinfligir:   {},
    avenir:         { modelo: "venir" },
    avergonzar:     { alternancia_vocálica: "o:ue" },
    averiar:        { modelo: "vaciar" },
    averiguar:      {},
    avisar:         {},
    avizorar:       {},
    ayudar:         {},
    bailar:         {},
    bajar:          {},
    balbucear:      {},
    balbucir:       {},  // No sigue el modelo "lucir" // FIX: Presente de indicativo: se usa más balbuceo que balbuzco (la forma regular ha desplazado a la irregular)
    bañar:          {},
    barrer:         {},
    basar:          {},
    bastar:         {},
    batir:          {},
    beber:          {},
    bendecir:       { modelo: "maldecir" },
    besar:          {},
    biografiar:     { modelo: "vaciar" },
    boicotear:      {},
    bordar:         {},
    bordear:        {},
    borrar:         {},
    brillar:        {},
    brindar:        {},
    brotar:         {},
    bruñir:         {},
    bucear:         {},
    bullir:         {},
    buscar:         {},
    caber:          { modelo: "caber",
                        tema_presente_yo_del_modelo: ["quep"],
                        tema_pretérito_del_modelo: "cup",
                        tema_futuro_del_modelo: "cabr"
                    },
    caer:           { tema_presente_yo_del_modelo: ["caig"] },
    calcular:       {},
    calentar:       { alternancia_vocálica: "e:ie" },
    calificar:      {},
    calmar:         {},
    calzar:         {},
    cambiar:        {},
    caminar:        {},
    cantar:         {},
    capacitar:      {},
    carcomer:       {},
    cargar:         {},
    casar:          {},
    catalogar:      {},
    categorizar:    {},
    causar:         {},
    cazar:          {},
    cegar:          { alternancia_vocálica: "e:ie" },
    celebrar:       {},
    cenar:          {},
    ceñir:          { alternancia_vocálica: "e:i" },
    censurar:       {},
    centrar:        {},
    cepillar:       {},
    cerner:         { alternancia_vocálica: "e:ie" },
    cernir:         { modelo: "cernir", alternancia_vocálica: "e:ie (cernir)" },
    cerrar:         { alternancia_vocálica: "e:ie" },
    cesar:          {},
    charlar:        {},
    chatear:        {},
    chirriar:       { modelo: "vaciar" },
    chismear:       {},
    chispear:       {},
    chocar:         {},
    chupar:         {},
    cimentar:       { alternancia_vocálica: "e:ie", acepta_regular: "primaria" },
    circular:       {},
    circunvenir:    { modelo: "venir" },
    citar:          {},
    clavar:         {},
    cobrar:         {},
    cocer:          { alternancia_vocálica: "o:ue",
                      tema_presente_yo_del_modelo: ["cuez"],
                        excepciones_léxicas: {
                            participio: ["cocido","cocho"],
                            reglas: {
                                SubPres: {temas: {p1:["coz"], p2:["coz"],            vos: [{"forma": "cuez","uso":"Riop."},{"forma":"coz","uso":"C.Am."}]}},
                                CmdPos:  {temas: {p1:["coz"]}}
                            }
                        }
                    },
    cocinar:        {},
    codiciar:       {},
    codificar:      {},
    cohibir:        { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    coincidir:      {},
    colar:          { alternancia_vocálica: "o:ue" },
    colgar:         { alternancia_vocálica: "o:ue" },
    colindar:       {},
    colocar:        {},
    colorar:        {},
    colorear:       {},
    combar:         {},
    comenzar:       { alternancia_vocálica: "e:ie" },
    comer:          {},
    comparar:       {},
    compartir:      {},
    compensar:      {},
    competir:       { alternancia_vocálica: "e:i" },
    complacer:      { modelo: "placer" },
    completar:      {},
    complicar:      {},
    componer:       { modelo: "poner" },
    comprar:        {},
    comprender:     {},
    comprobar:      { alternancia_vocálica: "o:ue" },
    comprometer:    {},
    comunicar:      {},
    concebir:       { modelo: "pedir" },
    concentrar:     {},
    conceptuar:     {},
    concernir:      { modelo: "cernir", impersonal: "gramatical" },
    concertar:      { alternancia_vocálica: "e:ie" },
    concienciar:    {},
    concluir:       {},
    concordar:      { alternancia_vocálica: "o:ue" },
    condenar:       {},
    condescender:   { alternancia_vocálica: "e:ie" },
    condicionar:    {},
    conducir:       { clase_conjugacional: "-ducir", tema_presente_yo_del_modelo: ["conduzc"], tema_pretérito_del_modelo: "conduj" },  // FIX: linguist: how can this pattern be generalized: "pretérito fuerte con -j" ?
    conectar:       {},
    confeccionar:   {},
    conferir:       { alternancia_vocálica: "e:ie" },
    confesar:       { alternancia_vocálica: "e:ie" },
    confiar:        { modelo: "vaciar" },
    confirmar:      {},
    confiscar:      {},
    confluir:       {},
    conformar:      {},
    confortar:      {},
    confundir:      {},
    congelar:       {},
    congestionar:   {},
    congregar:      {},
    conjeturar:     {},
    conjugar:       { modelo: null },   // regular, no sigue el modelo de "jugar"
    conjurar:       {},
    conmover:       { alternancia_vocálica: "o:ue" },
    conocer:        { modelo: "conocer", tema_presente_yo_del_modelo: ["conozc"] },
    conquerir:      { alternancia_vocálica: "e:ie" },
    conquistar:     {},
    conseguir:      { alternancia_vocálica: "e:i" },
    consensuar:     {},
    consentir:      { alternancia_vocálica: "e:ie" },
    conservar:      {},
    considerar:     {},
    consistir:      {},
    consolar:       { alternancia_vocálica: "o:ue" },
    constatar:      {},
    consternar:     {},
    constituir:     {},
    construir:      {},
    consultar:      {},
    consumir:       {},
    contactar:      {},
    contagiar:      {},
    contaminar:     {},
    contar:         { alternancia_vocálica: "o:ue",
                      excepciones_léxicas: {
                            reglas: {
                                // FIX: try to use temas instead
                                SubPres: { forms: { vos: [{"forma":"cuent/es","uso":"Riop."},{"forma":"cont/és","uso":"C.Am."}] }}
                            }
                        }
                    },
    contender:      { alternancia_vocálica: "e:ie" },
    contener:       {},
    contestar:      {},
    continuar:      {},
    contraer:       {},
    contrariar:     { modelo: "vaciar" },
    contrarrestar:  {},
    contratar:      {},
    contravenir:    { modelo: "venir" },
    contribuir:     {},
    controlar:      {},
    convenir:       { modelo: "venir" },
    conversar:      {},
    convertir:      { alternancia_vocálica: "e:ie" },
    convivir:       {},
    cooperar:       {},
    corear:         {},
    corregir:       { alternancia_vocálica: "e:i" },
    correr:         {},
    corresponder:   {},
    corroer:        { modelo: "roer" },
    cortar:         {},
    coser:          {},
    costar:         { alternancia_vocálica: "o:ue" },
    cotizar:        {},
    crear:          {},
    crecer:         {},
    creer:          {},
    criar:          { modelo: "vaciar",   // FIX: hay varias formas con dos variantes: tb. pre-2010
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: {suffixes: {p2: ["ais"], vos: ["as"]} },  // elimina tilde por RAE-2010
                                IndPret: {suffixes: {s1: ["e"], s3: ["o"]} },  // elimina tilde por RAE-2010
                                SubPres: {suffixes: {p2: ["eis"]}},  // elimina tilde por RAE-2010
                                CmdPos:  {suffixes: {vos: ["a"]} }  // elimina tilde por RAE-2010
                            }
                        }
                    },
    cruzar:         {},
    cuadrar:        {},
    cubrir:         { excepciones_léxicas: { participio: ["cubierto"] } },
    cuestionar:     {},
    cuidar:         {},
    cultivar:       {},
    cumplir:        {},
    curar:          {},
    currar:         {},
    custodiar:      {},
    dañar:          {},
    dar:            { modelo: "dar",
                      sufijo_presente_yo: "oy",
                      excepciones_léxicas: {
                            reglas: {
                                // The default "-ar" verb pattern of accent the last sylable doesn't apply to vos forms of "dar", since "dás" is only one sylable
                                IndPres: { suffixes: {                                                       p2: ["ais"],                       vos: null } },
                                SubPres: { suffixes: { s1: ["é"],                s3: ["é"],                  p2: ["eis"],                       vos: null } },
                                IndPret: { suffixes: { s1: ["i"], s2: ["iste"],  s3: ["io"],   p1: ["imos"], p2: ["isteis"], p3: ["ieron"] } },
                                CmdPos:  { suffixes: {                           s3: ["é"],                                                     vos: null  } }
                            }
                        }
                    },
    debatir:        {},
    deber:          { auxiliar: true },
    debilitar:      {},
    decaer:         {},
    decidir:        {},
    decir:          { modelo: "decir", 
                        tema_presente_yo_del_modelo: ["dig"],
                        tema_pretérito_del_modelo: "dij",
                        tema_futuro_del_modelo: "dir",
                        alternancia_vocálica: "e:i",
                        excepciones_léxicas: {
                            participio: ["dicho"],
                            gerundio: ["diciendo"],
                            imperativo_tú: ["di/"],
                        }
                    },
    declarar:       {},
    declinar:       {},
    dedicar:        {},
    defender:       { alternancia_vocálica: "e:ie" },
    deferir:        { alternancia_vocálica: "e:ie" },
    definir:        {},
    deformar:       {},
    degollar:       { alternancia_vocálica: "o:ue" },
    dejar:          {},
    deleitar:       {},
    delinquir:      {},
    delirar:        {},
    demoler:        { alternancia_vocálica: "o:ue" },
    demonizar:      {},
    demostrar:      { alternancia_vocálica: "o:ue" },
    denegar:        { alternancia_vocálica: "e:ie" },
    depender:       {},
    depositar:      {},
    depredar:       {},
    derramar:       {},
    derretir:       { alternancia_vocálica: "e:i" },
    derribar:       {},
    derrotar:       {},
    derruir:        {},
    desactivar:     {},
    desafiar:       { modelo: "vaciar" },
    desaguar:       {},
    desahijar:      {},
    desahogar:      {},
    desahuciar:     {},
    desalentar:     { alternancia_vocálica: "e:ie" },
    desaparecer:    {},
    desaprobar:     { alternancia_vocálica: "o:ue" },
    desarrollar:    {},
    desasir:        { tema_presente_yo_del_modelo: ["desasg"] },
    desatender:     { alternancia_vocálica: "e:ie" },
    desatinar:      {},
    desavenir:      { modelo: "venir" },
    desayunar:      {},
    desbaratar:     {},
    desbordar:      {},
    descafeinar:    { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    descansar:      {},
    descargar:      {},
    descartar:      {},
    descender:      { alternancia_vocálica: "e:ie" },
    descolgar:      { alternancia_vocálica: "o:ue" },
    descolorar:     {},
    desconcentrar:  {},
    desconceptuar:  {},
    desconectar:    {},
    desconfiar:     { modelo: "vaciar" },
    desconocer:     { modelo: "conocer" },
    descontar:      { alternancia_vocálica: "o:ue" },
    descreer:       {},
    describir:      { excepciones_léxicas: { participio: ["descrito"] } },
    descubrir:      { excepciones_léxicas: { participio: ["descubierto"] } },
    desdoblar:      {},
    desear:         {},
    desembocar:     {},
    desempeñar:     {},
    desenroscar:    {},
    desenvolver:    { modelo: "volver" },
    desesperanzar:  {},
    desesperar:     {},
    desestimar:     {},
    desfallecer:    {},
    desgajar:       {},
    desgarrar:      {},
    desgraciar:     {},
    deshabituar:    {},
    deshacer:       { modelo: "hacer" },
    deshierbar:     {},
    deshumanizar:   {},
    desistir:       {},
    desleír:        { modelo: "reír",
                        clase_conjugacional: "-eír",
                        excepciones_léxicas: {
                            reglas: {
                                // FIX: lingúista: es esto correcto?
                                // Note: este no es obvio... por qué hay dos raíces diferentes: "desl" y "desli"
                                // FIX: try to use temas y sufijos instead
                                //                      no existe variante sin tilde proviene de "reír"
                                IndPret: { forms: { s3: ["desl/ió"]   }},
                                //                      no existe variante sin tilde proviene de "reír"
                                SubPres: { forms: { p2: ["desli/áis"]   }},
                            }
                        }
                    },
    deslizar:       {},
    deslucir:       { modelo: "lucir"},
    desmontar:      {},
    desobedecer:    {},
    desosar:        { alternancia_vocálica: "o:ue", ponga_hiato: true },
    despachar:      {},
    desparramar:    {},
    despedir:       { alternancia_vocálica: "e:i" },
    despegar:       {},
    despejar:       {},
    despellejar:    {},
    desperdiciar:   {},
    despertar:      { alternancia_vocálica: "e:ie" },
    desplazar:      {},
    desplegar:      { alternancia_vocálica: "e:ie" },
    desplomar:      {},
    desplumar:      {},
    despojar:       {},
    despotricar:    {},
    despreciar:     {},
    desprender:     {},
    desproveer:     { modelo: "leer", excepciones_léxicas: { participio: ["desprovisto"] } },
    despuntar:      {},
    destartalar:    {},
    destellar:     {},
    desterrar:      { alternancia_vocálica: "e:ie" },
    destilar:       {},
    destituir:      {},
    destrozar:      {},
    destruir:       {},
    desvaír:        {},   // FIX:
    desvariar:      { modelo: "vaciar" },
    desviar:        { modelo: "vaciar" },
    desvirtuar:     {},
    detallar:       {},
    detener:        {},    // FIX: setting modelo causes a failure, but it should work     {modelo: "tener"},
    deteriorar:     {},
    determinar:     {},
    devaluar:       {},
    devastar:       {},
    devenir:        { modelo: "venir" },
    devolver:       { modelo: "volver" },
    dibujar:        {},
    dictar:         {},
    diferenciar:    {},
    diferir:        { alternancia_vocálica: "e:ie" },
    dificultar:     {},
    digerir:        { alternancia_vocálica: "e:ie" },
    dignar:         {},
    diluir:         {},
    dirigir:        {},
    discernir:      { modelo: "cernir" },
    disciplinar:    {},
    disculpar:      {},
    diseñar:        {},
    disentir:       { alternancia_vocálica: "e:ie" },
    disfrutar:      {},
    disminuir:      {},
    disolver:       { modelo: "volver" },
    disparar:       {},
    disponer:       {},
    distender:      { alternancia_vocálica: "e:ie" },
    distinguir:     {},
    distribuir:     {},
    disuadir:       {},
    divertir:       { alternancia_vocálica: "e:ie" },
    dividir:        {},
    divorciar:      {},
    divulgar:       {},
    doblar:         {},
    doblegar:       {},
    documentar:     {},
    doler:          { alternancia_vocálica: "o:ue" },
    dorar:          {},
    dormir:         { modelo: "dormir", alternancia_vocálica: "o:ue" },
    duchar:         {},
    dudar:          {},
    durar:          {},
    echar:          {},
    efectuar:       {},
    efluir:         {},
    ejercer:        { tema_presente_yo_del_modelo: ["ejerz"] },  // no sigue el modelo de conocer, no usa "zc"
    elaborar:       {},
    electrocutar:   {},
    elegir:         { alternancia_vocálica: "e:i" },
    elevar:         {},  // FIX: linguist: solo en varios regiones hay: alternancia_vocálica: "e:ie"
    eliminar:       {},
    eludir:         {},
    embadurnar:     {},
    embarcar:       {},
    embargar:       {},
    embarrar:       {},
    embestir:       { alternancia_vocálica: "e:i" },
    emborrachar:    {},
    emigrar:        {},
    emitir:         {},
    empacar:        {},
    empachar:       {},
    empañar:        {},
    empapar:        {},
    emparejar:      {},
    empatar:        {},
    empeorar:       {},
    emperejilar:    {},
    emperifollar:   {},
    empezar:        { alternancia_vocálica: "e:ie" },
    emplear:        {},
    emprender:      {},
    empujar:        {},
    enamorar:       {},
    encajar:        {},
    encaminar:      {},
    encantar:       {},
    encaramar:      {},
    encargar:       {},
    encender:       { alternancia_vocálica: "e:ie" },
    encerrar:       { alternancia_vocálica: "e:ie" },
    enchufar:       {},
    encoger:        {},
    encomendar:     { alternancia_vocálica: "e:ie" },
    encontrar:      { alternancia_vocálica: "o:ue" },
    enderezar:      {},
    enfermar:       {},
    enflaquecer:    {},
    enfrentar:      {},
    enfriar:        { modelo: "vaciar" },
    enfurecer:      {},
    engañar:        {},
    enganchar:      {},
    engordar:       {},
    engreír:        { modelo: "reír" },
    enjugar:        { modelo: null},  // regular, no sigue el modelo de "jugar"
    enlazar:        {},
    enloquecer:     {},
    enlucir:        { modelo: "lucir" },
    enmascarar:     {},
    enmendar:       { alternancia_vocálica: "e:ie" },
    enojar:         {},
    enraizar:       { modelo: "enraizar",
                        excepciones_léxicas: {
                            reglas: {
                                // FIX: lingüista: hay una regla por esta situación?
                                // FIX: perhaps replace this with stress_last_vowel_of_s123p3_stem?
                                IndPres: { forms: { s1: ["enraíz/o"], s2: ["enraíz/as"], s3: ["enraíz/a"],                              p3: ["enraíz/an"]}},
                                SubPres: { forms: { s1: ["enraíc/e"], s2: ["enraíc/es"], s3: ["enraíc/e"],                              p3: ["enraíc/en"], vos: [{"forma":"enraíc/es","uso":"Riop."},{"forma":"enraic/és","uso":"C.Am."}] }},
                                CmdPos:  { forms: { s2: ["enraíz/a"], s3: ["enraíc/e"],                                                 p3: ["enraíc/en"]}}
                            },
                        }
                    },
    enredar:        {},
    enroscar:       {},
    ensamblar:      {},
    ensanchar:      {},
    enseñar:        {},
    ensuciar:       {},
    entender:       { alternancia_vocálica: "e:ie" },
    enterar:        {},
    enterrar:       { alternancia_vocálica: "e:ie" },
    entrar:         {},
    entrechocar:    {},
    entregar:       {},
    entrelucir:     { modelo: "lucir" },
    entrever:       { modelo: "ver" },
    entrevistar:    {},
    entristecer:    {},
    entumecer:      {},
    entusiasmar:    {},
    envenenar:      {},
    enviar:         { modelo: "vaciar" },
    envidiar:       {},
    envolver:       { modelo: "volver" },
    erguir:         { modelo: "erguir",
                        alternancia_vocálica: "e:ie",
                        tema_presente_yo_del_modelo: ["irg", "yerg"],
                        excepciones_léxicas: {
                            gerundio: ["irguiendo"],
                            reglas: {
                                // FIX: lingüista: hay una regla por esta situación?
                                // FIX: perhaps replace this with temas y sufijos?
                                // FIX: it looks like the sufjios are regular?
                                IndPres: { forms: { s1: ["irg/o", "yerg/o"],       s2: ["irgu/es", "yergu/es"], s3: ["irgu/e", "yergu/e"],
                                                                                                            p3: ["irgu/en", "yergu/en"] }},
                                IndPret: { forms: {                                                         s3: ["irgu/ió"],
                                                                                                            p3: ["irgu/ieron"]} },
                                SubPres: { 
                                           // Según ChatGPT: hay un conflicto entre irregularidad heredada vs. regularización del voseo
                                           //    sí existe una forma voseante tipo yergás, pero en la práctica, muchas veces se dice ergás o se evita el verbo
                                           forms: { vos: [{"forma":"yerg/as","uso":"Riop."},{"forma":"irg/as","uso":"C.Am."},{"forma":"irg/ás","uso":"C.Am."}] }
                                        //    forms: { s1: ["irga", "yerga"],       s2: ["irgas", "yergas"],   s3: ["irga", "yerga"],
                                        //             p1:	["irgamos", "yergamos"], p2: ["irgáis", "yergáis"], p3: ["irgan", "yergan"], vos: ["yergas"] }
                                                 },
                                SubImp: { tema_suplicativo: ["irguie"], stress_last_char_of_p1_stem: true },
                                SubFut: { tema_suplicativo: ["irguie"], stress_last_char_of_p1_stem: true },
                                CmdPos: { forms: {                               s2: ["irgu/e", "yergu/e"],   s3:	["irg/a", "yerg/a"],
                                                   p1: ["irg/amos", "yerg/amos"],                             p3: ["irg/an", "yerg/an"] }}
                            },
                        }
                    },
    errar:          {}, // FIX: tiene dos formas
    eructar:        {},
    escabullir:     {},
    escalar:        {},
    escanear:       {},
    escapar:        {},
    escarchar:      {},
    escoger:        {},
    esconder:       {},
    escribir:       { excepciones_léxicas: { participio: ["escrito"] } },
    escuchar:       {},
    esculpir:       {},
    esforzar:       { alternancia_vocálica: "o:ue" },
    espantar:       {},
    esparcir:       { tema_presente_yo_del_modelo: ["esparz"] },
    esperar:        {},
    espiar:         { modelo: "vaciar" },
    esquiar:        { modelo: "vaciar" },
    establecer:     {},
    estacionar:     {},
    estafar:        {},
    estallar:       {},
    estancar:       {},
    estandarizar:   {},
    estar:         { modelo: "estar",
                        auxiliar: true,
                        sufijo_presente_yo: "oy",
                        tema_pretérito_del_modelo: "estuv", 
                        excepciones_léxicas: {
                            imperativo_tú: ["est/á"],
                            reglas: {
                                IndPres: { suffixes: {            s2: ["ás"], s3: ["á"], p3: ["án"]}},
                                IndPret: { suffixes: { s1: ["e"], s2: ["iste"], s3: ["o"],  p1: ["imos"],   p2: ["isteis"], p3: ["ieron"] } },
                                SubPres: { suffixes: { s1: ["é"], s2: ["és"], s3: ["é"], p3: ["én"],        vos: null }},
                                CmdPos:  { suffixes: {                       s3: ["é"], p3: ["én"]}}
                            }
                        }
                    },
    estatuir:       {},
    estimar:        {},
    estipular:      {},
    estofar:        {},
    estornudar:     {},
    estrangular:    {},
    estrechar:      {},
    estregar:       { alternancia_vocálica: "e:ie", acepta_regular: "variante" },
    estremecer:     {},
    estrenar:       {},
    estresar:       {},
    estropear:      {},
    estudiar:       {},
    evadir:         {},
    evaluar:        {},
    evitar:         {},
    examinar:       {},
    exasperar:      {},
    exceder:        {},
    exceptuar:      {},
    excluir:        {},
    exhalar:        {},
    exigir:         {},
    exiliar:        {},
    existir:        {},
    expandir:       {},
    expedir:        { alternancia_vocálica: "e:i" },
    expiar:         { modelo: "vaciar" },
    explicar:       {},
    explorar:       {},
    exponer:        {},
    expresar:       {},
    extender:       { alternancia_vocálica: "e:ie" },
    extenuar:       {},
    extinguir:      {},
    extraer:        {},
    extrañar:       {},
    fabricar:       {},
    facilitar:      {},
    facturar:       {},
    fallar:         {},
    fallecer:       {},
    faltar:         {},
    fascinar:       {},
    felicitar:      {},
    festejar:       {},
    figurar:        {},
    fijar:          {},
    finalizar:      {},
    fingir:         {},
    firmar:         {},
    flanquear:      {},
    flaquear:       {},
    flexionar:      {},
    flotar:         {},
    fluctuar:       {},
    fluir:          {},
    formar:         {},
    forzar:         { alternancia_vocálica: "o:ue" },
    fotografiar:    { modelo: "vaciar" },
    fraguar:        {},
    frecuentar:     {},
    fregar:         { alternancia_vocálica: "e:ie" },
    freír:          { modelo: "reír" },
    frotar:         {},
    fruncir:        { tema_presente_yo_del_modelo: ["frunz"] },
    fulgurar:       {},
    fumar:          {},
    funcionar:      {},
    fundir:         {},
    ganar:          {},
    gastar:         {},
    gemir:          { modelo: "pedir" },
    generar:        {},
    germinar:       {},
    girar:          {},
    gobernar:       { alternancia_vocálica: "e:ie" },
    gotear:         {},
    gozar:          {},
    grabar:         {},
    graduar:        {},
    granizar:       { impersonal: "natural" },
    gritar:         {},
    gruir:          {},
    gruñir:         {},
    guardar:        {},
    guiar:          { modelo: "guiar",
                        // clase_conjugacional: "-iar",
                        // TODO: hay formas reformadas en la reforma ortográfica de la RAE de 2010, considera añadir estas formas
                        // Otherwise, the accent is the only thing different from the regular forms
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { stress_last_vowel_of_s123p3_stem: true,
                                // FIX: perhaps replace this with temas o sufijos?
                                           forms:    {                                   p2: ["guia/is",{"forma":"guiá/is","uso":"pre-2010"}],
                                                                          vos: ["gui/as",{"forma":"gui/ás","uso":"pre-2010"}]   }},
                                IndPret: { forms:    { s1: ["gui/e",{"forma":"gui/é","uso":"pre-2010"}],          s3: ["gui/o",{"forma":"gui/ó","uso":"pre-2010"}],  } },
                                SubPres: { stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true,
                                        forms: {                                        p2: ["gui/eis",{"forma":"gui/éis","uso":"pre-2010"}] }},
                                CmdPos:  { stress_last_vowel_of_s123p3_stem: true,
                                        forms: {                                                               vos: ["gui/a"] }}
                            }
                        }
                    },
    guisar:         {},
    gustar:         {},
    haber:          { modelo: "haber",
                        tema_pretérito_del_modelo: "hub",
                        tema_futuro_del_modelo: "habr",
                        // impersonal: "estricto",  // Note: no modela esta situación rara de dos significados: auxiliar y impersonal estricto
                        auxiliar: true,
                        excepciones_léxicas: {
                            supletivo: true,
                                // FIX: perhaps replace this with temas y sufijos?  
                            imperativo_tú: [{"forma":"h/e","uso":"arcaico"},{"forma":"hab/e","uso":"arcaico"}],
                            reglas: {
                                IndPres: { forms: { s1: ["h/e"],     s2: ["h/as"],  s3: ["h/a", {forma: "h/ay", uso: "impersonal"}],     
                                                    p1: ["h/emos"],                p3: ["h/an"],   vos: null} },
                                SubPres: { tema_suplicativo: ["hay"] },
                                CmdPos:  { tema_suplicativo: ["hay"],
                                        forms: {                 p2: ["hab/ed"] ,              vos: null } }
                            }
                        }
                    },
    habitar:        {},
    habituar:       {},
    hablar:         {},
    hacer:          { modelo: "hacer",
                        clase_conjugacional: "-acer",
                        tema_presente_yo_del_modelo: ["hag"],
                        tema_pretérito_del_modelo: "hic",
                        tema_futuro_del_modelo: "har",
                        excepciones_léxicas: {
                            participio: ["hecho"],
                            imperativo_tú: ["haz/"],
                            reglas: {
                                // FIX: linguist: should "hizo" be managed with sound preserving transformations?
                                IndPret: { forms: {s3: ["hiz/o"]} },
                                SubPres: { forms: {vos: [{forma:"hag/as",uso:"Riop."}, {forma:"hag/ás",uso:"C.Am."}]} },
                            }
                        }
                    },
    halar:          {},
    hallar:         {},
    hartar:         {},
    heder:          { alternancia_vocálica: "e:ie" },
    helar:          { alternancia_vocálica: "e:ie" },
    hendir:         { modelo: "cernir" },
    herir:          { alternancia_vocálica: "e:ie" },
    herrar:         { alternancia_vocálica: "e:ie" },
    hervir:         { alternancia_vocálica: "e:ie" },
    hilvanar:       {},
    hornear:        {},
    hospedar:       {},
    huir:           { /* se conjuga de forma regular, solo hay reglas especiales de ortografía */ },
    humanizar:      {},
    humillar:       {},
    hundir:         {},
    identificar:    {},
    ignorar:        {},
    igualar:        {},
    iluminar:       {},
    imaginar:       {},
    imbuir:         {},
    impedir:        { alternancia_vocálica: "e:i" },
    implantar:      {},
    implicar:       {},
    implorar:       {},
    imponer:        {},
    importar:       {},
    imposibilitar:  {},
    impregnar:      {},
    impresionar:    {},
    imprimir:       { excepciones_léxicas: { participio: ["imprimido","impreso"] } },
    inclinar:       {},
    incluir:        {},
    incorporar:     {},
    incrementar:    {},
    incrustar:      {},
    incubar:        {},
    incumbir:       {},
    indagar:        {},
    indexar:        {},
    indicar:        {},
    inducir:        {},
    infectar:       {},
    inferir:        { alternancia_vocálica: "e:ie" },
    infestar:       {},
    infligir:       {},
    influir:        {},
    informar:       {},
    infundir:       {},
    ingeniar:       {},
    ingerir:        { alternancia_vocálica: "e:ie" },
    ingresar:       {},
    inhalar:        {},
    iniciar:        {},
    injerir:        { alternancia_vocálica: "e:ie" },
    inmigrar:       {},
    inmiscuir:      {},
    inmortalizar:   {},
    inmunizar:      {},
    inquietar:      {},
    inquirir:       { alternancia_vocálica: "i:ie" },
    inscribir:      { excepciones_léxicas: { participio: ["inscrito"] } },
    insertar:       {},
    insinuar:       {},
    insistir:       {},
    inspeccionar:   {},
    inspirar:       {},
    instalar:       {},
    instar:         {},
    instituir:      {},
    instruir:       {},
    integrar:       {},
    intentar:       {},
    interactuar:    {},
    intercalar:     {},
    intercambiar:   {},
    interesar:      {},
    interferir:     { alternancia_vocálica: "e:ie" },
    interpretar:    {},
    interrogar:     {},
    interrumpir:    {},
    intervenir:     { modelo: "venir" },
    intoxicar:      {},
    intrigar:       {},
    introducir:     {},
    intuir:         { /* modelo: "huir" */ },
    inundar:        {},
    invadir:        {},
    invertir:       { alternancia_vocálica: "e:ie" },
    investir:       { alternancia_vocálica: "e:i" },
    invitar:        {},
    ir:             { modelo: "ir",
                        auxiliar: true,
                        no_admite_prefijos: true,
                        tema_pretérito_del_modelo: "fu",
                        sufijo_presente_yo: "oy",
                        excepciones_léxicas: {
                            supletivo: true,
                            participio: ["ido"],
                            gerundio: ["yendo"],
                            reglas: {
                                // The default "-ir" verb pattern of accent the last sylable doesn't apply to vos forms of "ir", since "ir" is only one sylable
                                IndPres: { forms: { s1: ["v/oy"], s2: ["v/as"],    s3: ["v/a"],   p1: ["v/amos"],  p2: ["v/ais"],     p3: ["v/an"], vos: null } },
                                SubPres: { tema_suplicativo: ["vay"],
                                        forms: {                                            vos: [{"forma":"vay/as","uso":"Riop."},{"forma":"vay/ás","uso":"C.Am."}] }
                                },
                                IndPret: { forms: { s1: ["fu/i"], s2: ["fu/iste"], s3: ["fu/e"],  p1: ["fu/imos"], p2: ["fu/isteis"], p3: ["fu/eron"] } },
                                IndImp:  { forms: { s1: ["ib/a"], s2: ["ib/as"],   s3: ["ib/a"],  p1: ["íb/amos"], p2: ["ib/ais"],    p3: ["ib/an"] } },
                                // IndFut: uses regular conjugation
                                // IndCond: uses regular conjugation
                                CmdPos:  { forms: {              s2: ["v/e"],     s3: ["vay/a"], p1: ["vay/amos", "v/amos"],         p3: ["vay/an"], vos: ["and/á"] } }
                            }
                        }
                    },
    irritar:        {},
    jactar:         {},
    jalar:          {},
    josear:         {},
    jubilar:        {},
    jugar:          { alternancia_vocálica: "u:ue" },
    juntar:         {},
    jurar:          {},
    justificar:     {},
    juzgar:         {},
    lagrimear:      {},
    lamentar:       {},
    largar:         {},
    lastimar:       {},
    lavar:          {},
    leer:           { modelo: "leer", clase_conjugacional: "-eer" },
    levantar:       {},
    licenciar:      {},
    limpiar:        {},
    llamar:         {},
    llegar:         {},
    llenar:         {},
    llevar:         {},
    llorar:         {},
    llover:         { alternancia_vocálica: "o:ue", impersonal: "natural" },
    lloviznar:      { impersonal: "natural" },
    localizar:      {},
    lograr:         {},
    luchar:         {},
    lucir:          { modelo: "lucir", tema_presente_yo_del_modelo: ["luzc"] },
    lustrar:        {},
    maldecir:       { modelo: "maldecir", 
                        tema_presente_yo_del_modelo: ["maldig"],
                        tema_pretérito_del_modelo: "maldij",
                        alternancia_vocálica: "e:i",
                        excepciones_léxicas: {
                            imperativo_tú: ["maldic/e"],
                            participio: ["maldecido", "maldito"],
                        } 
                    },
    malgastar:      {},
    malquerer:      { modelo: "querer" },
    mandar:         {},
    manejar:        {},
    maniatar:       {},
    manifestar:     { alternancia_vocálica: "e:ie" },
    mantener:       {},
    maquillar:      {},
    marcar:         {},
    marchar:        {},
    martillar:      {},
    matar:          {},
    matchear:       {},
    maullar:        {},
    mecer:          { tema_presente_yo_del_modelo: ["mez"] },
    medir:          { alternancia_vocálica: "e:i" },
    meditar:        {},
    mejorar:        {},
    mencionar:      {},
    mendigar:       {},
    menguar:        {},
    menospreciar:   {},
    menstruar:      { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    } },
    mentar:         { alternancia_vocálica: "e:ie" },
    mentir:         { alternancia_vocálica: "e:ie" },
    merecer:        {},
    merendar:       { alternancia_vocálica: "e:ie" },
    meter:          {},
    mirar:          {},
    modelar:        {},
    modernizar:     {},
    modificar:      {},
    molestar:       {},
    monetizar:      {},
    montar:         {},
    morder:         { alternancia_vocálica: "o:ue" },
    morir:          { alternancia_vocálica: "o:ue", excepciones_léxicas: {participio: ["muerto"]} },
    mostrar:        { alternancia_vocálica: "o:ue" },
    mover:          { modelo: "mover", alternancia_vocálica: "o:ue" },
    mudar:          {},
    multiplicar:    {},
    murmurar:       {},
    nacer:          { tema_presente_yo_del_modelo: ["nazc"] },
    nadar:          {},
    necesitar:      {},
    negar:          { alternancia_vocálica: "e:ie" },
    nevar:          { alternancia_vocálica: "e:ie", impersonal: "natural" },
    nombrar:        {},
    normalizar:     {},
    notar:          {},
    nublar:         {},
    nutrir:         {},
    obedecer:       {},
    obligar:        {},
    observar:       {},
    obstruir:       {},
    obtener:        { modelo: "tener" },
    ocasionar:      {},
    ocluir:         {},
    ocupar:         {},
    ocurrir:        {},
    odiar:          {},
    ofrecer:        {},
    ofuscar:        {},
    oír:            { modelo: "oír",    // FIX: linguist: why is this a class?
                        tema_presente_yo_del_modelo: ["oig"],
                        excepciones_léxicas: {
                            reglas: {
                                CmdPos:  { suffixes: {                                                      p2: ["íd"],          } }
                            }
                        }
                    },
    oler:           { alternancia_vocálica: "o:ue" },
    olvidar:        {},
    operar:         {},
    oponer:         { modelo: "poner"},
    organizar:      {},
    originar:       {},
    orinar:         {},
    padecer:        {},
    pagar:          {},
    parar:          {},
    parecer:        {},
    parpadear:      {},
    participar:     {},
    partir:         {},
    partyar:        {},
    pasar:          {},
    pasear:         {},
    pasmar:         {},
    patear:         {},
    patinar:        {},
    patrullar:      {},
    pausar:         {},
    pedalear:       {},
    pedir:          { modelo: "pedir", 
                      alternancia_vocálica: "e:i",
                    //   excepciones_léxicas: {
                    //         reglas: {
                    //             SubPres: { 
                    //                 suffixes: { vos: [{"forma":"as","uso":"Riop."},{"forma":"ás","uso":"C.Am."}] }
                    //             }
                    //         }
                    //     }
                    },
    pegar:          {},
    peinar:         {},
    penetrar:       {},
    pensar:         { alternancia_vocálica: "e:ie",
                      excepciones_léxicas: {
                            reglas: {
                                SubPres: { forms: { vos: [{"forma":"piens/es","uso":"Riop."},{"forma":"pens/és","uso":"C.Am."}] }}
                            }
                        }
                    },
    perder:         { alternancia_vocálica: "e:ie" },
    perdonar:       {},
    perforar:       {},
    permanecer:     {},
    permitir:       {},
    perpetrar:      {},
    perpetuar:      {},
    perseguir:      { alternancia_vocálica: "e:i" },
    pertenecer:     {},
    pervertir:      { alternancia_vocálica: "e:ie" },
    pesar:          {},
    pescar:         {},
    pestañear:      {},
    petrificar:     {},
    piar:           { modelo: "vaciar",
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { forms: { p2: ["pi/ais",{"forma":"pi/áis","uso":"pre-2010"}],  vos: ["pi/as",{"forma":"pi/ás","uso":"pre-2010"}] }},
                                IndPret: { forms: { s1: ["pi/e",{"forma":"pi/é","uso":"pre-2010"}], s3: ["pi/o",{"forma":"pi/ó","uso":"pre-2010"}]} },
                                SubPres: { forms: { p2:["pi/eis",{"forma":"pi/éis","uso":"pre-2010"}] }},
                                CmdPos:  { forms: { vos:["pi/a",{"forma":"pi/á","uso":"pre-2010"}] }}
                            },
                        }
                    },
    picar:          {},
    picotear:       {},
    pintar:         {},
    pisar:          {},
    placer:         { modelo: "placer", tema_presente_yo_del_modelo: ["plazc"] },
    planchar:       {},
    planificar:     {},
    plasmar:        {},
    platicar:       {},
    plegar:         { alternancia_vocálica: "e:ie" },
    poblar:         { alternancia_vocálica: "o:ue" },
    poder:          { modelo: "poder",
                        auxiliar: true,
                        alternancia_vocálica: "o:ue",
                        tema_pretérito_del_modelo: "pud",
                        tema_futuro_del_modelo: "podr",
                        excepciones_léxicas: { gerundio_tema_cambio_excepcional: "o:u" }
                    },
    poner:          { modelo: "poner",
                        tema_presente_yo_del_modelo: ["pong"],
                        tema_pretérito_del_modelo: "pus",
                        tema_futuro_del_modelo: "pondr",
                        excepciones_léxicas: {
                            participio: ["puesto"],
                            imperativo_tú: ["pon/"],
                            reglas: {
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    pordiosear:     {},
    portar:         {},
    posar:          {},
    poseer:         {},
    practicar:      {},
    precluir:       {},
    preferir:       { alternancia_vocálica: "e:ie" },
    preguntar:      {},
    prender:        {},
    preocupar:      {},
    preparar:       {},
    presenciar:     {},
    presentar:      {},
    presentir:      { alternancia_vocálica: "e:ie" },
    presionar:      {},
    prestar:        {},
    pretender:      {},
    prevenir:       { modelo: "venir" },
    prever:         { modelo: "ver" },
    principiar:     {},
    probar:         { alternancia_vocálica: "o:ue" },
    proceder:       {},
    procesar:       {},
    procurar:       {},
    producir:       {},
    proferir:       { alternancia_vocálica: "e:ie" },
    prohibir:       { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    prohijar:       {},
    proliferar:     {},
    prometer:       {},
    promover:       { alternancia_vocálica: "o:ue" },
    pronunciar:     {},
    proponer:       {},
    proporcionar:   {},
    propugnar:      {},
    proseguir:      { alternancia_vocálica: "e:i" },
    prostituir:     {},
    proteger:       {},
    proveer:        { excepciones_léxicas: { participio: ["proveído", "provisto"] } },
    provenir:       { modelo: "venir" },
    provocar:       {},
    publicar:       {},
    pudrir:         { excepciones_léxicas: { participio: ["podrido"] } },
    pulir:          {},
    puntuar:        {},
    quebrantar:     {},
    quebrar:        { alternancia_vocálica: "e:ie" },
    quedar:         {},
    quejar:         {},
    quemar:         {},
    querer:         { modelo: "querer",
                        tema_pretérito_del_modelo: "quis",
                        tema_futuro_del_modelo: "querr",
                        alternancia_vocálica: "e:ie"
                    },
    quitar:         {},
    radicar:        {},
    ramificar:      {},
    raspar:         {},
    rastrear:       {},
    realizar:       {},
    reanudar:       {},
    rearmar:        {},
    rebanar:        {},
    rebelar:        {},
    rebosar:        {},
    recetar:        {},
    rechazar:       {},
    rechinar:       {},
    recibir:        {},
    reciclar:       {},
    reclamar:       {},
    recluir:        {},
    recobrar:       {},
    recocer:        { alternancia_vocálica: "o:ue",
                      tema_presente_yo_del_modelo: ["recuez"],
                        excepciones_léxicas: {
                            reglas: {
                                SubPres: {temas: {p1:["recoz"], p2:["recoz"],            vos: [{"forma": "recuez","uso":"Riop."},{"forma":"recoz","uso":"C.Am."}]}},
                                CmdPos:  {temas: {p1:["recoz"]}}
                            }
                        }
                    },
    recoger:        {},
    recolectar:     {},
    recomendar:     { alternancia_vocálica: "e:ie" },
    recomenzar:     { alternancia_vocálica: "e:ie" },
    reconfortar:    {},
    reconocer:      { modelo: "conocer" },
    reconstituir:   {},
    reconstruir:    {},
    recontar:       { alternancia_vocálica: "o:ue" },
    reconvenir:     { modelo: "venir" },
    recordar:       { alternancia_vocálica: "o:ue" },
    recorrer:       {},
    recuperar:      {},
    recurrir:       {},
    redistribuir:   {},
    redituar:       {},
    reducir:        {},
    reemplazar:     {},
    reencontrar:    { alternancia_vocálica: "o:ue" },
    reenviar:       { modelo: "vaciar" },
    reevaluar:      {},
    referir:        { alternancia_vocálica: "e:ie" },
    reflejar:       {},
    refluir:        {},
    reformar:       {},
    reforzar:       { alternancia_vocálica: "o:ue" },
    refugiar:       {},
    refutar:        {},
    regalar:        {},
    regañar:        {},
    regar:          { alternancia_vocálica: "e:ie" },
    regir:          { alternancia_vocálica: "e:i" },
    registrar:      {},
    regresar:       {},
    regular:        {},
    rehilar:        { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    rehogar:        {},
    rehuir:         {},
    rehusar:        {},
    reinstalar:     {},
    reír:           { modelo: "reír",
                        alternancia_vocálica: "e:í",
                        excepciones_léxicas: {
                            participio: ["reído"],
                            reglas: {
                                // FIX: linguist: are there other reglas I can use?
                                // FIX: bring in alternate forms
                                // FIX: must formalize the relationship of CmdPos on SubPres
                                IndPres: { stress_last_vowel_of_s123p3_stem: true,
                                    // FIX: considera un campo "formas_adicionales", para que no tengamos repetir la forma que no cambia
                                    // FIX: es posible que podamos usar una regla de ortografía (rompe el diptongo) por el resto?
                                           forms: {s1: ["rí/o"], /* s2: ["ríes"], s3: ["ríe"],*/ p1: ["re/ímos"], p2: ["re/ís"],  /*p3: ["ríen"],   vos: ["reís"], */}},
                                IndPret: { forms: {                           s3: ["r/io",{"forma":"r/ió","uso":"pre-2010"}],                               /* p3: ["rieron"],*/} },
                                SubPres: { tema_suplicativo: ["rí"], stress_last_vowel_of_s123p3_stem: true,
                                           forms: {                          p1: ["ri/amos"], p2: ["ri/ais",{"forma":"ri/áis","uso":"pre-2010"}], /*p3: ["rían"]*/ }},
                                CmdPos:  { tema_suplicativo: ["rí"],
                                           forms: {                                        p1: ["ri/amos"], p2: ["re/íd"],                  vos: ["re/í"]}}
                            },
                        }
                    },
    relajar:        {},
    relampaguear:   {},
    relucir:        { modelo: "lucir" },
    rememorar:      {},
    remendar:       { alternancia_vocálica: "e:ie" },
    remodelar:      {},
    remorder:       { alternancia_vocálica: "o:ue" },
    remover:        { alternancia_vocálica: "o:ue" },
    remplazar:      {},
    rendir:         { modelo: "pedir" },
    reñir:          { alternancia_vocálica: "e:i" },
    renovar:        { alternancia_vocálica: "o:ue" },
    renunciar:      {},
    reparar:        {},
    repartir:       {},
    repasar:        {},
    repercutir:     {},
    repetir:        { alternancia_vocálica: "e:i" },
    replicar:       {},
    reposar:        {},
    representar:    {},
    reprimir:       {},
    reprobar:       { alternancia_vocálica: "o:ue" },
    requerir:       { alternancia_vocálica: "e:ie" },
    resbalar:       {},
    resentir:       { alternancia_vocálica: "e:ie" },
    resfriar:       { modelo: "vaciar" },
    resistir:       {},
    resollar:       { alternancia_vocálica: "o:ue" },
    resolver:       { modelo: "mover", excepciones_léxicas: {participio: ["resuelto"]} },
    respetar:       {},
    respirar:       {},
    resplandecer:   {},
    responder:      {},
    restar:         {},
    restaurar:      {},
    restituir:      {},
    restringir:     {},
    resultar:       {},
    retener:        { modelo: "tener" },
    retorcer:       { // Nota: es muy similar con "cocer", FIX: posiblemente otro patrón de cambios de la raíz?
                      // FIX: simplifica como prefijo="re" + "torcer"
                        alternancia_vocálica: "o:ue",
                        tema_presente_yo_del_modelo: ["retuerz"],
                        excepciones_léxicas: {
                            reglas: {
                                SubPres: {temas: {p1:["retorz"], p2:["retorz"],            vos: [{"forma": "retuerz","uso":"Riop."},{"forma":"retorz","uso":"C.Am."}]}},
                                CmdPos:  {temas: {p1:["retorz"]}}
                            }
                        }
                    },
    retornar:       {},
    retozar:        {},
    retribuir:      {},
    retumbar:       {},
    reunir:         { alternancia_vocálica: "u:ú" },
    revaluar:       {},
    revelar:        {},
    reventar:       { alternancia_vocálica: "e:ie" },
    revertir:       { alternancia_vocálica: "e:ie" },
    revisar:        {},
    revolver:       { modelo: "volver" },
    rezagar:        {},
    rimar:          {},
    robar:          {},
    rociar:         { modelo: "vaciar" },
    rodar:          { alternancia_vocálica: "o:ue" },
    roer:           { modelo: "roer", tema_presente_yo_del_modelo: ["roig", "roy"], acepta_regular: "primaria",
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { temas: {vos: ["ro"]} },
                                SubPres: { forms: {vos: [{"forma": "ro/as","uso":"Riop."},{"forma":"ro/ás","uso":"C.Am."}]} },
                                CmdPos:  { temas: {vos: ["ro"]} },
                            }
                        }
                    },
    rogar:          { alternancia_vocálica: "o:ue" },
    romper:         { excepciones_léxicas: { participio: ["roto"] } },
    rondar:         {},
    rozar:          {},
    rugir:          {},
    saber:          { modelo: "saber",
                        tema_pretérito_del_modelo: "sup",
                        tema_futuro_del_modelo: "sabr",
                        excepciones_léxicas: {
                            reglas: {
                                // similar a caber
                                IndPres: { forms: { s1: ["s/é"] } },
                                SubPres: { tema_suplicativo: ["sep"] },
                                CmdPos:  { forms: {                                s3: ["sep/a"],  p1: ["sep/amos"],                     p3: ["sep/an"] } }
                            }
                        }
                    },
    saborear:       {},
    sacar:          {},
    saciar:         {},
    sacudir:        {},
    sahumar:        {},
    saldar:         {},
    salir:          { modelo: "salir",
                        tema_presente_yo_del_modelo: ["salg"],
                        tema_futuro_del_modelo: "saldr",
                        excepciones_léxicas: { imperativo_tú: ["sal/"] }
                    },
    salpimentar:    { alternancia_vocálica: "e:ie" },
    saludar:        {},
    sanar:          {},
    sangrar:        {},
    santiguar:      {},
    satisfacer:     { modelo: "hacer" },
    secar:          {},
    secuestrar:     {},
    seducir:        {},
    seguir:         {
                        // NOTE: this does not conjugate as a "-uir" clase infinitivo
                        tema_presente_yo_del_modelo: ["sig"],
                        alternancia_vocálica: "e:i",
                    },
    seleccionar:    {},
    sellar:         {},
    sembrar:        { alternancia_vocálica: "e:ie" },
    señalar:        {},
    sentar:         { alternancia_vocálica: "e:ie" },
    sentir:         { alternancia_vocálica: "e:ie" },
    separar:        {},
    ser:            { modelo: "ser",
                        auxiliar: true,
                        no_admite_prefijos: true,
                        tema_pretérito_del_modelo: "fu",
                        excepciones_léxicas: {
                            supletivo: true,
                            reglas: {
                                IndPres: { forms: { s1: ["s/oy"], s2: ["er/es"],   s3: ["/es"],    p1: ["s/omos"],  p2: ["s/ois"],     p3: ["s/on"],    vos: ["s/os"] } },
                                IndImp:  { forms: { s1: ["er/a"], s2: ["er/as"],   s3: ["er/a"],   p1: ["ér/amos"], p2: ["er/ais"],    p3: ["er/an"]}},
                                IndPret: { forms: { s1: ["fu/i"], s2: ["fu/iste"], s3: ["fu/e"],   p1: ["fu/imos"], p2: ["fu/isteis"], p3: ["fu/eron"] } },
                                SubPres: { tema_suplicativo: ["se"],
                                           forms: {                                             vos: [{"forma":"se/as","uso":"Riop."},{"forma":"se/ás","uso":"C.Am."}] }},
                                CmdPos:  { forms: {              s2: ["sé/"],     s3: ["s/ea"],   p1: ["se/amos"],                   p3: ["se/an"],   vos: null} }
                            }
                        }
                    },
    serrar:         { alternancia_vocálica: "e:ie" },
    servir:         { alternancia_vocálica: "e:i" },
    sesgar:         {},
    significar:     {},
    simplificar:    {},
    sincerar:       {},
    situar:         {},
    sobar:          {},
    sobrecargar:    {},
    sobrecoger:     {},
    sobrehilar:     { excepciones_léxicas: {
                        reglas: {
                            IndPres: {stress_last_vowel_of_s123p3_stem: true},
                            SubPres: {stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true},
                            CmdPos: {stress_last_vowel_of_s123p3_stem: true}
                        }
                    }},
    sobresalir:     {},
    sobrevenir:     { modelo: "venir" },
    sobrevivir:     {},
    sofreír:        { modelo: "reír" },
    solar:          { alternancia_vocálica: "o:ue" },
    soldar:         { alternancia_vocálica: "o:ue" },
    soler:          { alternancia_vocálica: "o:ue", impersonal: "soler" },
    solicitar:      {},
    sollozar:       {},
    soltar:         { alternancia_vocálica: "o:ue" },
    solucionar:     {},
    someter:        {},
    sonar:          { alternancia_vocálica: "o:ue" },
    soñar:          { alternancia_vocálica: "o:ue" },
    sonreír:        { modelo: "reír" },
    soportar:       {},
    sorprender:     {},
    sortear:        {},
    sosegar:        { alternancia_vocálica: "e:ie" },
    sospechar:      {},
    sostener:       {},
    soterrar:       {},
    subir:          {},
    substituir:     {},
    substraer:      {},
    subvenir:       { modelo: "venir" },
    subvertir:      { alternancia_vocálica: "e:ie" },
    succionar:      {},
    suceder:        {},
    sudar:          {},
    sufrir:         {},
    sugerir:        { alternancia_vocálica: "e:ie" },
    sujetar:        {},
    sumar:          {},
    suministrar:    {},
    suplicar:       {},
    suponer:        {},
    supurar:        {},
    surgir:         {},
    suscribir:      { excepciones_léxicas: { participio: ["suscrito"] } },
    suspender:      {},
    suspirar:       {},
    sustentar:      {},
    sustituir:      {},
    sustraer:       {},
    tallar:         {},
    tañer:          {},
    tapar:          {},
    tapiar:         {},
    tardar:         {},
    tartamudear:    {},
    tatuar:         {},
    teclear:        {},
    temblar:        { alternancia_vocálica: "e:ie" },
    temer:          {},
    templar:        {},
    tender:         { alternancia_vocálica: "e:ie" },
    tener:          { modelo: "tener", 
                        auxiliar: true,
                        tema_presente_yo_del_modelo: ["teng"],
                        tema_pretérito_del_modelo: "tuv",
                        tema_futuro_del_modelo: "tendr",
                        alternancia_vocálica: "e:ie",
                        excepciones_léxicas: {
                            imperativo_tú: ["ten/"],
                            reglas: {
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    teñir:          { alternancia_vocálica: "e:i" },
    tentar:         { alternancia_vocálica: "e:ie" },
    terminar:       {},
    textear:        {},
    tipificar:      {},
    tirar:          {},
    titubear:       {},
    tocar:          {},
    tolerar:        {},
    tomar:          {},
    torcer:         { // Nota: es muy similar con "cocer", FIX: posiblemente otro patrón de cambios de la raíz?
                        alternancia_vocálica: "o:ue",
                        tema_presente_yo_del_modelo: ["tuerz"],
                        excepciones_léxicas: {
                            reglas: {
                                SubPres: {temas: {p1:["torz"], p2:["torz"],            vos: [{"forma": "tuerz","uso":"Riop."},{"forma":"torz","uso":"C.Am."}]}},
                                CmdPos:  {temas: {p1:["torz"]}}
                            }
                        }
                    },
    tornar:         {},
    torturar:       {},
    toser:          {},
    tostar:         { alternancia_vocálica: "o:ue" },
    trabajar:       {},
    traducir:       {},
    traer:          { modelo: "traer", tema_presente_yo_del_modelo: ["traig"], tema_pretérito_del_modelo: "traj" },
    tramitar:       {},
    transcender:    { alternancia_vocálica: "e:ie" },
    transcurrir:    {},
    transferir:     { alternancia_vocálica: "e:ie" },
    transformar:    {},
    translucir:     { modelo: "lucir" },
    transmitir:     {},
    transportar:    {},
    trapear:        {},
    trascender:     { alternancia_vocálica: "e:ie" },
    trasferir:      { alternancia_vocálica: "e:ie" },
    trasladar:      {},
    traslucir:      { modelo: "lucir" },
    traspasar:      {},
    trastabillar:   {},
    tratar:         {},
    trepar:         {},
    triangular:     {},
    triturar:       {},
    trocar:         { alternancia_vocálica: "o:ue" },
    tronar:         { alternancia_vocálica: "o:ue" },
    tropezar:       { alternancia_vocálica: "e:ie" },
    tumbar:         {},
    turnar:         {},
    ubicar:         {},
    unir:           {},
    urgir:          {},
    usar:           {},
    utilizar:       {},
    vaciar:         { modelo: "vaciar",
                        clase_conjugacional: "-iar",
                        // FIX: linguist: The accent is the only thing different from the regular forms
                        // Is this due to an orthographic rule? or something else?
                        excepciones_léxicas: {
                            reglas: {
                                IndPres: { stress_last_vowel_of_s123p3_stem: true },
                                SubPres: { stress_last_vowel_of_s123p3_stem: true, stress_last_char_of_vos_riop_stem: true },
                                CmdPos:  { stress_last_vowel_of_s123p3_stem: true }
                            }
                        }
                    },
    vacilar:        {},
    valer:          { modelo: "valer", tema_presente_yo_del_modelo: ["valg"], tema_futuro_del_modelo: "valdr" },
    validar:        {},
    valuar:         {},
    variar:         { modelo: "vaciar" },
    velar:          {},
    vencer:         { tema_presente_yo_del_modelo: ["venz"]},
    vender:         {},
    venir:          { modelo: "venir",
                        tema_presente_yo_del_modelo: ["veng"],
                        tema_pretérito_del_modelo: "vin",
                        tema_futuro_del_modelo: "vendr",
                        alternancia_vocálica: "e:ie",
                        excepciones_léxicas: {
                            gerundio: ["viniendo"],
                            imperativo_tú: ["ven/"],
                            reglas: {
                                SubPres: {forms: {vos:[{"forma":"veng/as","uso":"Riop."},{"forma":"veng/ás","uso":"C.Am."}] }},
                                CmdPos:  { derivations: {preserve_stress_from_base: ["s2"] }}
                            }
                        }
                    },
    ventear:        {},
    ver:            { modelo: "ver",
                        // parece que no conforma bien a estas reglas
                        // sí prefijo_ind_pres_yo cambia, pero no con "g", y no con los mismos cambios
                        // no aplican ni tema_pretérito_del_modelo ni tema_futuro_del_modelo ni alternancia_vocálica
                        // el resto son excepciones_léxicas
                        excepciones_léxicas: {
                            gerundio: ["viendo"],
                            participio: ["visto"],
                            // hay varias excepciones_léxicas que probablemente tienen que ver con el hecho que ver es solo una sílaba
                            reglas: {
                                // p2 => accent dropped
                                // The default "-er" verb pattern of accent the last sylable doesn't apply to vos forms of "ver", since "vés" is only one sylable
                                IndPres: { suffixes: { s1: ["eo"],                                              p2: ["eis"],                        vos: null },
                                           derivations: {preserve_stress_from_base: ["s2","s3","p2","p3"]}
                                        },
                                SubPres: { tema_suplicativo: ["ve"] },
                                // accents dropped
                                IndPret: { forms: { s1: ["v/i"], s3: ["v/io"] },
                                           derivations: {preserve_stress_from_base: ["s1", "s3"]}
                                        },
                                IndImp: { tema_suplicativo: ["ve" ]},
                                CmdPos: { forms: {                      s3: ["ve/a"],           p1: ["ve/amos"],               p3: ["ve/an"],            vos: null },
                                          derivations: {preserve_stress_from_base: ["s2"] }
                                        }
                            }
                        }
                    },
    verraquear:     {},
    verter:         { alternancia_vocálica: "e:ie" },
    vestir:         { alternancia_vocálica: "e:i" },
    viajar:         {},
    vidriar:        { modelo: "vaciar", acepta_regular: "variante" },
    vigilar:        {},
    vincular:       {},
    violar:         {},
    virar:          {},
    visitar:        {},
    vivir:          {},
    volar:          { alternancia_vocálica: "o:ue"},
    volcar:         { alternancia_vocálica: "o:ue" },
    voltear:        {},
    volver:         { modelo: "volver", alternancia_vocálica: "o:ue", excepciones_léxicas: { participio: ["vuelto"] } },
    vomitar:        {},
    votar:          {},
    xerografiar:    { modelo: "vaciar" },
    yacer:          { tema_presente_yo_del_modelo: ["yazc", "yazg", "yag"],
                        excepciones_léxicas: {
                            reglas: {
                                SubPres: { forms: {vos: [{"forma":"yazc/as","uso":"Riop."},{"forma":"yazg/as","uso":"C.Am."}]}
                            
                                }
                            }
                        }
                    },
    zaherir:        { alternancia_vocálica: "e:ie" },
    zambuir:        {},
    zambullir:      {},
    zampar:         {},
    zarandear:      {},
    zumbar:         {},
}


export function getAnnotations(infinitivo: string, modelo: ModeloConjugacional, mood_tense_derivation: ConjugationOrDerivation) : VerbConjugationAnnotation {
    const annotations: VerbConjugationAnnotation = {infinitivo, mood_tense_derivation, modelo, version, license}
    return annotations
}
